/*
 * App URI: 2025-04-04/design35277
 * Source Location: 2025-04-04/design35277.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5542), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("2025-04-04/design35277", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// Generated JavaScript File for design35277.clx
			console.log('JavaScript for design35277 loaded.');;
			// End - User Script
			
			// Header
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("group_e7fed42f");
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container("group_ab46b1b2");
				var xYLayout_3 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_3);
				(function(container){
					var group_3 = new cpr.controls.Container("group_628d4049");
					var xYLayout_4 = new cpr.controls.layouts.XYLayout();
					group_3.setLayout(xYLayout_4);
					(function(container){
						var output_1 = new cpr.controls.Output("output_21dc2e27");
						output_1.value = "자료제공 세부지침";
						container.addChild(output_1, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "297.0px",
							"height": "28.0px"
						});
					})(group_3);
					container.addChild(group_3, {
						"top": "0.0px",
						"left": "491.5px",
						"width": "297.0px",
						"height": "28.0px"
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "0.0px",
					"left": "0.0px",
					"width": "1280.0px",
					"height": "60.0px"
				});
				var group_4 = new cpr.controls.Container("group_7797bce3");
				var xYLayout_5 = new cpr.controls.layouts.XYLayout();
				group_4.setLayout(xYLayout_5);
				(function(container){
					var group_5 = new cpr.controls.Container("group_ba626678");
					var xYLayout_6 = new cpr.controls.layouts.XYLayout();
					group_5.setLayout(xYLayout_6);
					(function(container){
						var group_6 = new cpr.controls.Container("group_1dd2c980");
						group_6.style.css({
							"border-bottom-color" : "#c6c6c6",
							"border-left-color" : "#c6c6c6",
							"border-top-color" : "#c6c6c6",
							"border-right-color" : "#c6c6c6"
						});
						var xYLayout_7 = new cpr.controls.layouts.XYLayout();
						group_6.setLayout(xYLayout_7);
						(function(container){
							var group_7 = new cpr.controls.Container("group_18cfd941");
							var xYLayout_8 = new cpr.controls.layouts.XYLayout();
							group_7.setLayout(xYLayout_8);
							(function(container){
								var group_8 = new cpr.controls.Container("group_dafc4a0a");
								var xYLayout_9 = new cpr.controls.layouts.XYLayout();
								group_8.setLayout(xYLayout_9);
								(function(container){
									var output_2 = new cpr.controls.Output("output_91186673");
									output_2.value = "갑상선암의 역학적 특성조사, 협력병기, 간암병기, 폐암병기 등의 표본조사자료 및 사망원인 연계자료, 맞춤형자료를 제공하고 있습니다.             ";
									container.addChild(output_2, {
										"top": "0.0px",
										"left": "0.0px",
										"width": "1216.0px",
										"height": "42.0px"
									});
								})(group_8);
								container.addChild(group_8, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "1216.0px",
									"height": "42.0px"
								});
								var group_9 = new cpr.controls.Container("group_9d80c8e6");
								var xYLayout_10 = new cpr.controls.layouts.XYLayout();
								group_9.setLayout(xYLayout_10);
								(function(container){
									var button_1 = new cpr.controls.Button("instance_fa2485b7");
									button_1.value = "자료제공 절차";
									button_1.style.css({
										"border-bottom-color" : "#d8d8d8",
										"border-left-color" : "#d8d8d8",
										"border-top-color" : "#d8d8d8",
										"border-right-color" : "#d8d8d8"
									});
									container.addChild(button_1, {
										"top": "0.0px",
										"left": "0.0px",
										"width": "608.0px",
										"height": "56.0px"
									});
									var button_2 = new cpr.controls.Button("instance_d24113bd");
									button_2.value = "자료제공 세부지침";
									button_2.style.css({
										"border-bottom-color" : "#003574",
										"border-left-color" : "#003574",
										"border-top-color" : "#003574",
										"border-right-color" : "#003574"
									});
									container.addChild(button_2, {
										"top": "0.0px",
										"left": "608.0px",
										"width": "608.0px",
										"height": "56.0px"
									});
								})(group_9);
								container.addChild(group_9, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "1216.0px",
									"height": "56.0px"
								});
								var group_10 = new cpr.controls.Container("group_df2cf5fb");
								var xYLayout_11 = new cpr.controls.layouts.XYLayout();
								group_10.setLayout(xYLayout_11);
								(function(container){
									var group_11 = new cpr.controls.Container("group_99a6148c");
									var xYLayout_12 = new cpr.controls.layouts.XYLayout();
									group_11.setLayout(xYLayout_12);
									(function(container){
										var output_3 = new cpr.controls.Output("output_53b249cf");
										output_3.value = "자료제공 세부지침";
										container.addChild(output_3, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "1216.0px",
											"height": "18.0px"
										});
									})(group_11);
									container.addChild(group_11, {
										"top": "0.0px",
										"left": "0.0px",
										"width": "1216.0px",
										"height": "18.0px"
									});
									var group_12 = new cpr.controls.Container("group_ca727edf");
									var xYLayout_13 = new cpr.controls.layouts.XYLayout();
									group_12.setLayout(xYLayout_13);
									(function(container){
										var output_4 = new cpr.controls.Output("output_4499c453");
										output_4.value = "이용자의 의무";
										container.addChild(output_4, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "1216.0px",
											"height": "18.0px"
										});
										var output_5 = new cpr.controls.Output("output_a7b4a93b");
										output_5.value = "1. 지정된 이용자 이외에는 자료를 열람해서는 안 됩니다\u20282. 사전에 명시한 목적 외에 자료 이용을 해서는 안 됩니다\u20283. 제공된 자료를 제삼자에게 유출해서는 안 됩니다\u20284. 목적 달성 또는 자료 보유 기간 만료 후 즉시 파기하여야 합니다\u20285. 자료 내 정보를 이용하여 개인을 식별하거나 접촉해서는 안 됩니다\u20286. 개별자료에 의거 알게 된 사항에 대해 누설해서는 안 됩니다\u2028\u203b 위 사항을 위반할 경우 중앙암등록본부는 이용자에게 자료의 파기 또는 반환을 요구할 수 있으며, 향후 제공자료 이용에 제한될 수 있습니다.";
										container.addChild(output_5, {
											"top": "50.0px",
											"left": "0.0px",
											"width": "1216.0px",
											"height": "168.0px"
										});
									})(group_12);
									container.addChild(group_12, {
										"top": "0.0px",
										"left": "0.0px",
										"width": "1216.0px",
										"height": "218.0px"
									});
									var group_13 = new cpr.controls.Container("group_e4a7edb4");
									var xYLayout_14 = new cpr.controls.layouts.XYLayout();
									group_13.setLayout(xYLayout_14);
									(function(container){
										var output_6 = new cpr.controls.Output("output_aaca567a");
										output_6.value = "자료제공비용";
										container.addChild(output_6, {
											"top": "0.0px",
											"left": "0.0px",
											"width": "1216.0px",
											"height": "18.0px"
										});
										var group_14 = new cpr.controls.Container("group_9c1b5d09");
										var xYLayout_15 = new cpr.controls.layouts.XYLayout();
										group_14.setLayout(xYLayout_15);
										(function(container){
											var output_7 = new cpr.controls.Output("output_6bba6e06");
											output_7.value = "\u203b 비용의 수납 및 회계 처리는 국립암센터 회계관계 규정이 정하는 바에 따릅니다";
											container.addChild(output_7, {
												"top": "0.0px",
												"left": "0.0px",
												"width": "1224.0px",
												"height": "12.0px"
											});
											var group_15 = new cpr.controls.Container("group_3d79b611");
											var xYLayout_16 = new cpr.controls.layouts.XYLayout();
											group_15.setLayout(xYLayout_16);
											(function(container){
												var group_16 = new cpr.controls.Container("group_c72dc467");
												var xYLayout_17 = new cpr.controls.layouts.XYLayout();
												group_16.setLayout(xYLayout_17);
												(function(container){
													var button_3 = new cpr.controls.Button("instance_3fc77c77");
													button_3.value = "비용산정기준";
													container.addChild(button_3, {
														"top": "0.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "12.0px"
													});
													var group_17 = new cpr.controls.Container("group_5ee31008");
													var xYLayout_18 = new cpr.controls.layouts.XYLayout();
													group_17.setLayout(xYLayout_18);
													(function(container){
														var output_8 = new cpr.controls.Output("output_8af9fe82");
														output_8.value = "통계표";
														container.addChild(output_8, {
															"top": "0.0px",
															"left": "0.0px",
															"width": "600.0px",
															"height": "12.0px"
														});
													})(group_17);
													container.addChild(group_17, {
														"top": "52.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "12.0px"
													});
													var grid_1 = new cpr.controls.Grid("grd944faaa0");
													grid_1.init({
														"columns": [
															{"width": "100px"},
															{"width": "100px"},
															{"width": "100px"},
															{"width": "100px"},
															{"width": "100px"}
														],
														"header": {
															"rows": [{"height": "24px"}],
															"cells": [
																{
																	"constraint": {"rowIndex": 0, "colIndex": 0},
																	"configurator": function(cell){
																	}
																},
																{
																	"constraint": {"rowIndex": 0, "colIndex": 1},
																	"configurator": function(cell){
																	}
																},
																{
																	"constraint": {"rowIndex": 0, "colIndex": 2},
																	"configurator": function(cell){
																	}
																},
																{
																	"constraint": {"rowIndex": 0, "colIndex": 3},
																	"configurator": function(cell){
																	}
																},
																{
																	"constraint": {"rowIndex": 0, "colIndex": 4},
																	"configurator": function(cell){
																	}
																}
															]
														},
														"detail": {
															"rows": [{"height": "24px"}],
															"cells": [
																{
																	"constraint": {"rowIndex": 0, "colIndex": 0},
																	"configurator": function(cell){
																	}
																},
																{
																	"constraint": {"rowIndex": 0, "colIndex": 1},
																	"configurator": function(cell){
																	}
																},
																{
																	"constraint": {"rowIndex": 0, "colIndex": 2},
																	"configurator": function(cell){
																	}
																},
																{
																	"constraint": {"rowIndex": 0, "colIndex": 3},
																	"configurator": function(cell){
																	}
																},
																{
																	"constraint": {"rowIndex": 0, "colIndex": 4},
																	"configurator": function(cell){
																	}
																}
															]
														}
													});
													container.addChild(grid_1, {
														"top": "102.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "224.0px"
													});
													var output_9 = new cpr.controls.Output("output_af57b6c3");
													output_9.value = "제공 표 개수 별 수수료 책정";
													container.addChild(output_9, {
														"top": "80.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "12.0px"
													});
													var group_18 = new cpr.controls.Container("group_69818cbb");
													var xYLayout_19 = new cpr.controls.layouts.XYLayout();
													group_18.setLayout(xYLayout_19);
													(function(container){
														var button_4 = new cpr.controls.Button("instance_c26dc9e6");
														button_4.value = "Button";
														button_4.style.css({
															"background-color" : "#F7F7F7",
															"border-bottom-color" : "#e4e4e4",
															"border-left-color" : "#e4e4e4",
															"border-top-color" : "#e4e4e4",
															"border-right-color" : "#e4e4e4",
															"background-image" : "none"
														});
														container.addChild(button_4, {
															"top": "0.0px",
															"left": "0.0px",
															"width": "600.0px",
															"height": "75.0px"
														});
													})(group_18);
													container.addChild(group_18, {
														"top": "346.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "98.0px"
													});
												})(group_16);
												container.addChild(group_16, {
													"top": "0.0px",
													"left": "0.0px",
													"width": "600.0px",
													"height": "440.0px"
												});
												var group_19 = new cpr.controls.Container("group_f4254630");
												var xYLayout_20 = new cpr.controls.layouts.XYLayout();
												group_19.setLayout(xYLayout_20);
												(function(container){
													var button_5 = new cpr.controls.Button("instance_fb4b36b2");
													button_5.value = "비용산정기준";
													container.addChild(button_5, {
														"top": "0.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "12.0px"
													});
													var group_20 = new cpr.controls.Container("group_6ba3663b");
													var xYLayout_21 = new cpr.controls.layouts.XYLayout();
													group_20.setLayout(xYLayout_21);
													(function(container){
														var output_10 = new cpr.controls.Output("output_4004d172");
														output_10.value = "원자료 자료연계";
														container.addChild(output_10, {
															"top": "0.0px",
															"left": "0.0px",
															"width": "600.0px",
															"height": "12.0px"
														});
													})(group_20);
													container.addChild(group_20, {
														"top": "52.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "12.0px"
													});
													var group_21 = new cpr.controls.Container("group_af9b7407");
													var xYLayout_22 = new cpr.controls.layouts.XYLayout();
													group_21.setLayout(xYLayout_22);
													(function(container){
														var group_22 = new cpr.controls.Container("group_da12c8bf");
														var xYLayout_23 = new cpr.controls.layouts.XYLayout();
														group_22.setLayout(xYLayout_23);
														(function(container){
															var group_23 = new cpr.controls.Container("group_3611fa5f");
															var xYLayout_24 = new cpr.controls.layouts.XYLayout();
															group_23.setLayout(xYLayout_24);
															(function(container){
																var group_24 = new cpr.controls.Container("group_9817721f");
																group_24.style.css({
																	"background-color" : "#FFFBE5",
																	"border-bottom-color" : "#c6c6c6",
																	"border-left-color" : "#c6c6c6",
																	"border-top-color" : "#c6c6c6",
																	"border-right-color" : "#c6c6c6"
																});
																var xYLayout_25 = new cpr.controls.layouts.XYLayout();
																group_24.setLayout(xYLayout_25);
																(function(container){
																	var output_11 = new cpr.controls.Output("output_e05a6b90");
																	output_11.value = "제공 건 구간";
																	container.addChild(output_11, {
																		"top": "0.0px",
																		"left": "16.0px",
																		"width": "248.0px",
																		"height": "80.0px"
																	});
																})(group_24);
																container.addChild(group_24, {
																	"top": "0.0px",
																	"left": "0.0px",
																	"width": "280.0px",
																	"height": "80.0px"
																});
																var group_25 = new cpr.controls.Container("group_0f8216f5");
																var xYLayout_26 = new cpr.controls.layouts.XYLayout();
																group_25.setLayout(xYLayout_26);
																(function(container){
																	var group_26 = new cpr.controls.Container("group_60049eea");
																	group_26.style.css({
																		"background-color" : "#FFFBE5",
																		"border-bottom-color" : "#c6c6c6",
																		"border-left-color" : "#c6c6c6",
																		"border-top-color" : "#c6c6c6",
																		"border-right-color" : "#c6c6c6"
																	});
																	var xYLayout_27 = new cpr.controls.layouts.XYLayout();
																	group_26.setLayout(xYLayout_27);
																	(function(container){
																		var output_12 = new cpr.controls.Output("output_ffcb3e9c");
																		output_12.value = "수수료";
																		container.addChild(output_12, {
																			"top": "14.5px",
																			"left": "16.0px",
																			"width": "288.0px",
																			"height": "11.0px"
																		});
																	})(group_26);
																	container.addChild(group_26, {
																		"top": "0.0px",
																		"left": "0.0px",
																		"width": "320.0px",
																		"height": "40.0px"
																	});
																	var group_27 = new cpr.controls.Container("group_2f2ea94f");
																	group_27.style.css({
																		"background-color" : "#FFFBE5",
																		"border-bottom-color" : "#c6c6c6",
																		"border-left-color" : "#c6c6c6",
																		"border-top-color" : "#c6c6c6",
																		"border-right-color" : "#c6c6c6"
																	});
																	var xYLayout_28 = new cpr.controls.layouts.XYLayout();
																	group_27.setLayout(xYLayout_28);
																	(function(container){
																		var output_13 = new cpr.controls.Output("output_7f13c9e7");
																		output_13.value = "기본";
																		container.addChild(output_13, {
																			"top": "14.5px",
																			"left": "16.0px",
																			"width": "144.0px",
																			"height": "11.0px"
																		});
																		var output_14 = new cpr.controls.Output("output_5f89daad");
																		output_14.value = "추가";
																		container.addChild(output_14, {
																			"top": "14.5px",
																			"left": "170.0px",
																			"width": "144.0px",
																			"height": "11.0px"
																		});
																	})(group_27);
																	container.addChild(group_27, {
																		"top": "40.0px",
																		"left": "0.0px",
																		"width": "320.0px",
																		"height": "40.0px"
																	});
																})(group_25);
																container.addChild(group_25, {
																	"top": "0.0px",
																	"left": "280.0px",
																	"width": "320.0px",
																	"height": "80.0px"
																});
															})(group_23);
															container.addChild(group_23, {
																"top": "0.0px",
																"left": "0.0px",
																"width": "600.0px",
																"height": "80.0px"
															});
															var group_28 = new cpr.controls.Container("group_5186e4be");
															var xYLayout_29 = new cpr.controls.layouts.XYLayout();
															group_28.setLayout(xYLayout_29);
															(function(container){
																var group_29 = new cpr.controls.Container("group_9c0a3bd2");
																group_29.style.css({
																	"border-bottom-color" : "#d8d8d8",
																	"border-left-color" : "#d8d8d8",
																	"border-top-color" : "#d8d8d8",
																	"border-right-color" : "#d8d8d8"
																});
																var xYLayout_30 = new cpr.controls.layouts.XYLayout();
																group_29.setLayout(xYLayout_30);
																(function(container){
																	var output_15 = new cpr.controls.Output("output_3d762ae4");
																	output_15.value = "10만 건 이하";
																	container.addChild(output_15, {
																		"top": "18.0px",
																		"left": "16.0px",
																		"width": "248.0px",
																		"height": "12.0px"
																	});
																})(group_29);
																container.addChild(group_29, {
																	"top": "0.0px",
																	"left": "0.0px",
																	"width": "280.0px",
																	"height": "48.0px"
																});
																var group_30 = new cpr.controls.Container("group_88f62ce2");
																group_30.style.css({
																	"border-bottom-color" : "#d8d8d8",
																	"border-left-color" : "#d8d8d8",
																	"border-top-color" : "#d8d8d8",
																	"border-right-color" : "#d8d8d8"
																});
																var xYLayout_31 = new cpr.controls.layouts.XYLayout();
																group_30.setLayout(xYLayout_31);
																(function(container){
																	var output_16 = new cpr.controls.Output("output_520c60aa");
																	output_16.value = "100,000원/개";
																	container.addChild(output_16, {
																		"top": "18.0px",
																		"left": "31.0px",
																		"width": "98.0px",
																		"height": "12.0px"
																	});
																})(group_30);
																container.addChild(group_30, {
																	"top": "0.0px",
																	"left": "280.0px",
																	"width": "160.0px",
																	"height": "48.0px"
																});
																var group_31 = new cpr.controls.Container("group_f6715fcd");
																group_31.style.css({
																	"border-bottom-color" : "#d8d8d8",
																	"border-left-color" : "#d8d8d8",
																	"border-top-color" : "#d8d8d8",
																	"border-right-color" : "#d8d8d8"
																});
																var xYLayout_32 = new cpr.controls.layouts.XYLayout();
																group_31.setLayout(xYLayout_32);
																(function(container){
																	var output_17 = new cpr.controls.Output("output_fc221918");
																	output_17.value = "-";
																	container.addChild(output_17, {
																		"top": "18.0px",
																		"left": "75.0px",
																		"width": "10.0px",
																		"height": "12.0px"
																	});
																})(group_31);
																container.addChild(group_31, {
																	"top": "0.0px",
																	"left": "440.0px",
																	"width": "160.0px",
																	"height": "48.0px"
																});
															})(group_28);
															container.addChild(group_28, {
																"top": "80.0px",
																"left": "0.0px",
																"width": "600.0px",
																"height": "48.0px"
															});
															var group_32 = new cpr.controls.Container("group_ca5a5b9d");
															var xYLayout_33 = new cpr.controls.layouts.XYLayout();
															group_32.setLayout(xYLayout_33);
															(function(container){
																var group_33 = new cpr.controls.Container("group_2124f034");
																group_33.style.css({
																	"border-bottom-color" : "#d8d8d8",
																	"border-left-color" : "#d8d8d8",
																	"border-top-color" : "#d8d8d8",
																	"border-right-color" : "#d8d8d8"
																});
																var xYLayout_34 = new cpr.controls.layouts.XYLayout();
																group_33.setLayout(xYLayout_34);
																(function(container){
																	var output_18 = new cpr.controls.Output("output_5992cd48");
																	output_18.value = "10만 건 초과";
																	container.addChild(output_18, {
																		"top": "31.0px",
																		"left": "16.0px",
																		"width": "248.0px",
																		"height": "12.0px"
																	});
																})(group_33);
																container.addChild(group_33, {
																	"top": "0.0px",
																	"left": "0.0px",
																	"width": "280.0px",
																	"height": "74.0px"
																});
																var group_34 = new cpr.controls.Container("group_37842da0");
																group_34.style.css({
																	"border-bottom-color" : "#d8d8d8",
																	"border-left-color" : "#d8d8d8",
																	"border-top-color" : "#d8d8d8",
																	"border-right-color" : "#d8d8d8"
																});
																var xYLayout_35 = new cpr.controls.layouts.XYLayout();
																group_34.setLayout(xYLayout_35);
																(function(container){
																	var output_19 = new cpr.controls.Output("output_5af68f1f");
																	output_19.value = "300,000원 \u203b 감액미대상";
																	container.addChild(output_19, {
																		"top": "18.0px",
																		"left": "33.0px",
																		"width": "94.0px",
																		"height": "38.0px"
																	});
																})(group_34);
																container.addChild(group_34, {
																	"top": "0.0px",
																	"left": "280.0px",
																	"width": "160.0px",
																	"height": "74.0px"
																});
																var group_35 = new cpr.controls.Container("group_21ca54be");
																group_35.style.css({
																	"border-bottom-color" : "#d8d8d8",
																	"border-left-color" : "#d8d8d8",
																	"border-top-color" : "#d8d8d8",
																	"border-right-color" : "#d8d8d8"
																});
																var xYLayout_36 = new cpr.controls.layouts.XYLayout();
																group_35.setLayout(xYLayout_36);
																(function(container){
																	var output_20 = new cpr.controls.Output("output_0b9fb087");
																	output_20.value = "3원/건";
																	container.addChild(output_20, {
																		"top": "31.0px",
																		"left": "57.5px",
																		"width": "45.0px",
																		"height": "12.0px"
																	});
																})(group_35);
																container.addChild(group_35, {
																	"top": "0.0px",
																	"left": "440.0px",
																	"width": "160.0px",
																	"height": "74.0px"
																});
															})(group_32);
															container.addChild(group_32, {
																"top": "128.0px",
																"left": "0.0px",
																"width": "600.0px",
																"height": "74.0px"
															});
														})(group_22);
														container.addChild(group_22, {
															"top": "0.0px",
															"left": "0.0px",
															"width": "600.0px",
															"height": "202.0px"
														});
													})(group_21);
													container.addChild(group_21, {
														"top": "102.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "202.0px"
													});
													var output_21 = new cpr.controls.Output("output_d117ba06");
													output_21.value = "제공 건 구간별 수수료 책정 (상한액 : 1,000만원)";
													container.addChild(output_21, {
														"top": "80.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "12.0px"
													});
													var group_36 = new cpr.controls.Container("group_bb35febb");
													var xYLayout_37 = new cpr.controls.layouts.XYLayout();
													group_36.setLayout(xYLayout_37);
													(function(container){
														var button_6 = new cpr.controls.Button("instance_456b23f3");
														button_6.value = "Button";
														button_6.style.css({
															"background-color" : "#F7F7F7",
															"border-bottom-color" : "#e4e4e4",
															"border-left-color" : "#e4e4e4",
															"border-top-color" : "#e4e4e4",
															"border-right-color" : "#e4e4e4",
															"background-image" : "none"
														});
														container.addChild(button_6, {
															"top": "0.0px",
															"left": "0.0px",
															"width": "600.0px",
															"height": "75.0px"
														});
													})(group_36);
													container.addChild(group_36, {
														"top": "346.0px",
														"left": "0.0px",
														"width": "600.0px",
														"height": "98.0px"
													});
												})(group_19);
												container.addChild(group_19, {
													"top": "0.0px",
													"left": "624.0px",
													"width": "600.0px",
													"height": "440.0px"
												});
											})(group_15);
											container.addChild(group_15, {
												"top": "36.0px",
												"left": "0.0px",
												"width": "1224.0px",
												"height": "440.0px"
											});
										})(group_14);
										container.addChild(group_14, {
											"top": "50.0px",
											"left": "0.0px",
											"width": "1224.0px",
											"height": "480.0px"
										});
										var group_37 = new cpr.controls.Container("group_7cab2ada");
										var xYLayout_38 = new cpr.controls.layouts.XYLayout();
										group_37.setLayout(xYLayout_38);
										(function(container){
											var output_22 = new cpr.controls.Output("output_25d3786c");
											output_22.value = "비용감면기준";
											container.addChild(output_22, {
												"top": "0.0px",
												"left": "0.0px",
												"width": "1216.0px",
												"height": "18.0px"
											});
											var grid_2 = new cpr.controls.Grid("grdcd0ce765");
											grid_2.init({
												"columns": [
													{"width": "100px"},
													{"width": "100px"},
													{"width": "100px"},
													{"width": "100px"},
													{"width": "100px"}
												],
												"header": {
													"rows": [{"height": "24px"}],
													"cells": [
														{
															"constraint": {"rowIndex": 0, "colIndex": 0},
															"configurator": function(cell){
															}
														},
														{
															"constraint": {"rowIndex": 0, "colIndex": 1},
															"configurator": function(cell){
															}
														},
														{
															"constraint": {"rowIndex": 0, "colIndex": 2},
															"configurator": function(cell){
															}
														},
														{
															"constraint": {"rowIndex": 0, "colIndex": 3},
															"configurator": function(cell){
															}
														},
														{
															"constraint": {"rowIndex": 0, "colIndex": 4},
															"configurator": function(cell){
															}
														}
													]
												},
												"detail": {
													"rows": [{"height": "24px"}],
													"cells": [
														{
															"constraint": {"rowIndex": 0, "colIndex": 0},
															"configurator": function(cell){
															}
														},
														{
															"constraint": {"rowIndex": 0, "colIndex": 1},
															"configurator": function(cell){
															}
														},
														{
															"constraint": {"rowIndex": 0, "colIndex": 2},
															"configurator": function(cell){
															}
														},
														{
															"constraint": {"rowIndex": 0, "colIndex": 3},
															"configurator": function(cell){
															}
														},
														{
															"constraint": {"rowIndex": 0, "colIndex": 4},
															"configurator": function(cell){
															}
														}
													]
												}
											});
											container.addChild(grid_2, {
												"top": "50.0px",
												"left": "0.0px",
												"width": "1216.0px",
												"height": "828.0px"
											});
										})(group_37);
										container.addChild(group_37, {
											"top": "562.0px",
											"left": "0.0px",
											"width": "1216.0px",
											"height": "878.0px"
										});
									})(group_13);
									container.addChild(group_13, {
										"top": "258.0px",
										"left": "0.0px",
										"width": "1216.0px",
										"height": "1440.0px"
									});
								})(group_10);
								container.addChild(group_10, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "1216.0px",
									"height": "1698.0px"
								});
							})(group_7);
							container.addChild(group_7, {
								"top": "32.0px",
								"left": "32.0px",
								"width": "1216.0px",
								"height": "1698.0px"
							});
						})(group_6);
						container.addChild(group_6, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "1280.0px",
							"height": "1810.0px"
						});
					})(group_5);
					container.addChild(group_5, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "1280.0px",
						"height": "1810.0px"
					});
				})(group_4);
				container.addChild(group_4, {
					"top": "60.0px",
					"left": "0.0px",
					"width": "1280.0px",
					"height": "1810.0px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0.0px",
				"left": "0.0px",
				"width": "1280.0px",
				"height": "1864.0px"
			});
		}
	});
	app.title = "design35277";
	cpr.core.Platform.INSTANCE.register(app);
})();
