/*
 * App URI: 2025-04-04/design28931
 * Source Location: 2025-04-04/design28931.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5542), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("2025-04-04/design28931", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// Generated JavaScript File for design28931.clx
			console.log('JavaScript for design28931 loaded.');;
			// End - User Script
			
			// Header
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			
			// UI Configuration
		}
	});
	app.title = "design28931";
	cpr.core.Platform.INSTANCE.register(app);
})();
