/*
 * App URI: 2025-04-04/design72167
 * Source Location: 2025-04-04/design72167.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5542), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("2025-04-04/design72167", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// Generated JavaScript File for design72167.clx
			console.log('JavaScript for design72167 loaded.');;
			// End - User Script
			
			// Header
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("group_07748087");
			group_1.style.css({
				"background-color" : "#FFFFFF"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container("group_f45234a4");
				var xYLayout_3 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_3);
				(function(container){
					var output_1 = new cpr.controls.Output("output_db9c2dab");
					output_1.value = "✏️ button";
					container.addChild(output_1, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "354.0px",
						"height": "100.0px"
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "100.0px",
					"left": "110.0px",
					"width": "1700.0px",
					"height": "100.0px"
				});
				var group_3 = new cpr.controls.Container("group_0e215391");
				group_3.style.css({
					"border-bottom-color" : "#d8d8d8",
					"border-left-color" : "#d8d8d8",
					"border-top-color" : "#d8d8d8",
					"border-right-color" : "#d8d8d8"
				});
				var xYLayout_4 = new cpr.controls.layouts.XYLayout();
				group_3.setLayout(xYLayout_4);
				(function(container){
					var output_2 = new cpr.controls.Output("output_ea83daf7");
					output_2.value = "버튼";
					container.addChild(output_2, {
						"top": "80.0px",
						"left": "100.0px",
						"width": "89.0px",
						"height": "12.0px"
					});
					var button_1 = new cpr.controls.Button("instance_65d0479f");
					button_1.value = "Button";
					button_1.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_1, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_3 = new cpr.controls.Output("output_dc24e8d0");
					output_3.value = "버튼";
					container.addChild(output_3, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_2 = new cpr.controls.Button("instance_4495564e");
					button_2.value = "Button";
					button_2.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_2, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_3 = new cpr.controls.Button("instance_6fff879a");
					button_3.value = "Button";
					button_3.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_3, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_4 = new cpr.controls.Output("output_fb91d9a7");
					output_4.value = "버튼";
					container.addChild(output_4, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_4 = new cpr.controls.Button("instance_fc7a011d");
					button_4.value = "Button";
					button_4.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_4, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_5 = new cpr.controls.Button("instance_3ee4902a");
					button_5.value = "Button";
					container.addChild(button_5, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_5 = new cpr.controls.Output("output_996d5502");
					output_5.value = "버튼";
					container.addChild(output_5, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_6 = new cpr.controls.Button("instance_1e68904c");
					button_6.value = "Button";
					container.addChild(button_6, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_7 = new cpr.controls.Button("instance_d817b953");
					button_7.value = "Button";
					container.addChild(button_7, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_6 = new cpr.controls.Output("output_c0dcc895");
					output_6.value = "버튼";
					container.addChild(output_6, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_8 = new cpr.controls.Button("instance_45cbf4b1");
					button_8.value = "Button";
					container.addChild(button_8, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_9 = new cpr.controls.Button("instance_ab3dc8fd");
					button_9.value = "Button";
					container.addChild(button_9, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_7 = new cpr.controls.Output("output_40b1eb3d");
					output_7.value = "버튼";
					container.addChild(output_7, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_10 = new cpr.controls.Button("instance_0dcef130");
					button_10.value = "Button";
					container.addChild(button_10, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_11 = new cpr.controls.Button("instance_5cde9106");
					button_11.value = "Button";
					container.addChild(button_11, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_8 = new cpr.controls.Output("output_1972e960");
					output_8.value = "버튼";
					container.addChild(output_8, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_12 = new cpr.controls.Button("instance_4d7e04bb");
					button_12.value = "Button";
					container.addChild(button_12, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_13 = new cpr.controls.Button("instance_6305b51c");
					button_13.value = "Button";
					container.addChild(button_13, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_9 = new cpr.controls.Output("output_f65b208f");
					output_9.value = "버튼";
					container.addChild(output_9, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_14 = new cpr.controls.Button("instance_af1724c3");
					button_14.value = "Button";
					container.addChild(button_14, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_15 = new cpr.controls.Button("instance_d2f857cc");
					button_15.value = "Button";
					container.addChild(button_15, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_10 = new cpr.controls.Output("output_e9f4b810");
					output_10.value = "버튼";
					container.addChild(output_10, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_16 = new cpr.controls.Button("instance_2ac0cec0");
					button_16.value = "Button";
					container.addChild(button_16, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_17 = new cpr.controls.Button("instance_0fc3df72");
					button_17.value = "Button";
					button_17.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_17, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_11 = new cpr.controls.Output("output_53ca92a5");
					output_11.value = "버튼";
					container.addChild(output_11, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_18 = new cpr.controls.Button("instance_f1c77b75");
					button_18.value = "Button";
					button_18.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_18, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_19 = new cpr.controls.Button("instance_3a555562");
					button_19.value = "Button";
					button_19.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_19, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_12 = new cpr.controls.Output("output_146e41b6");
					output_12.value = "버튼";
					container.addChild(output_12, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_20 = new cpr.controls.Button("instance_4e2db561");
					button_20.value = "Button";
					button_20.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_20, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_21 = new cpr.controls.Button("instance_942a50ec");
					button_21.value = "Button";
					container.addChild(button_21, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_13 = new cpr.controls.Output("output_814fc11c");
					output_13.value = "버튼";
					container.addChild(output_13, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_22 = new cpr.controls.Button("instance_5443067c");
					button_22.value = "Button";
					container.addChild(button_22, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_23 = new cpr.controls.Button("instance_cada6539");
					button_23.value = "Button";
					container.addChild(button_23, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_14 = new cpr.controls.Output("output_01ebdeb6");
					output_14.value = "버튼";
					container.addChild(output_14, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_24 = new cpr.controls.Button("instance_c106b743");
					button_24.value = "Button";
					container.addChild(button_24, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_25 = new cpr.controls.Button("instance_0f76c14d");
					button_25.value = "Button";
					container.addChild(button_25, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_15 = new cpr.controls.Output("output_17a1c548");
					output_15.value = "버튼";
					container.addChild(output_15, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_26 = new cpr.controls.Button("instance_e71fe72e");
					button_26.value = "Button";
					container.addChild(button_26, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_27 = new cpr.controls.Button("instance_791ed326");
					button_27.value = "Button";
					container.addChild(button_27, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_16 = new cpr.controls.Output("output_1006318d");
					output_16.value = "버튼";
					container.addChild(output_16, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_28 = new cpr.controls.Button("instance_42349746");
					button_28.value = "Button";
					container.addChild(button_28, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_29 = new cpr.controls.Button("instance_4a0dc1ae");
					button_29.value = "Button";
					container.addChild(button_29, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_17 = new cpr.controls.Output("output_6af37b4e");
					output_17.value = "버튼";
					container.addChild(output_17, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_30 = new cpr.controls.Button("instance_76c459c7");
					button_30.value = "Button";
					container.addChild(button_30, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_31 = new cpr.controls.Button("instance_78634bf2");
					button_31.value = "Button";
					button_31.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_31, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_18 = new cpr.controls.Output("output_6976c209");
					output_18.value = "버튼";
					container.addChild(output_18, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_32 = new cpr.controls.Button("instance_efe29685");
					button_32.value = "Button";
					button_32.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_32, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_33 = new cpr.controls.Button("instance_b3c2cbf7");
					button_33.value = "Button";
					container.addChild(button_33, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_19 = new cpr.controls.Output("output_4d6771f3");
					output_19.value = "버튼";
					container.addChild(output_19, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_34 = new cpr.controls.Button("instance_5817cea8");
					button_34.value = "Button";
					container.addChild(button_34, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_35 = new cpr.controls.Button("instance_c41a64bc");
					button_35.value = "Button";
					button_35.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_35, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_20 = new cpr.controls.Output("output_b02aa77b");
					output_20.value = "버튼";
					container.addChild(output_20, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_36 = new cpr.controls.Button("instance_c68a81a7");
					button_36.value = "Button";
					button_36.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_36, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_37 = new cpr.controls.Button("instance_4e4f31ca");
					button_37.value = "Button";
					container.addChild(button_37, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_21 = new cpr.controls.Output("output_93c6cad5");
					output_21.value = "버튼";
					container.addChild(output_21, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_38 = new cpr.controls.Button("instance_5e85fda4");
					button_38.value = "Button";
					container.addChild(button_38, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_39 = new cpr.controls.Button("instance_4fb16c23");
					button_39.value = "Button";
					button_39.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_39, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_22 = new cpr.controls.Output("output_3e954680");
					output_22.value = "버튼";
					container.addChild(output_22, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_40 = new cpr.controls.Button("instance_edcaab0a");
					button_40.value = "Button";
					button_40.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_40, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_41 = new cpr.controls.Button("instance_49de507b");
					button_41.value = "Button";
					container.addChild(button_41, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_23 = new cpr.controls.Output("output_a4380044");
					output_23.value = "버튼";
					container.addChild(output_23, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_42 = new cpr.controls.Button("instance_2b7ec810");
					button_42.value = "Button";
					container.addChild(button_42, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_43 = new cpr.controls.Button("instance_e0e2babd");
					button_43.value = "Button";
					container.addChild(button_43, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_24 = new cpr.controls.Output("output_0d6749b3");
					output_24.value = "버튼";
					container.addChild(output_24, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_44 = new cpr.controls.Button("instance_20da457b");
					button_44.value = "Button";
					container.addChild(button_44, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_45 = new cpr.controls.Button("instance_40c60cee");
					button_45.value = "Button";
					container.addChild(button_45, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_25 = new cpr.controls.Output("output_2fe4deaa");
					output_25.value = "버튼";
					container.addChild(output_25, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_46 = new cpr.controls.Button("instance_94ca4abe");
					button_46.value = "Button";
					container.addChild(button_46, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_47 = new cpr.controls.Button("instance_068c03c0");
					button_47.value = "Button";
					button_47.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_47, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_26 = new cpr.controls.Output("output_e6099f54");
					output_26.value = "버튼";
					container.addChild(output_26, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_48 = new cpr.controls.Button("instance_50ac5a5c");
					button_48.value = "Button";
					button_48.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_48, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_49 = new cpr.controls.Button("instance_762f22b8");
					button_49.value = "Button";
					container.addChild(button_49, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_27 = new cpr.controls.Output("output_84d01ba7");
					output_27.value = "버튼";
					container.addChild(output_27, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_50 = new cpr.controls.Button("instance_50696dec");
					button_50.value = "Button";
					container.addChild(button_50, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_51 = new cpr.controls.Button("instance_52ed80c9");
					button_51.value = "Button";
					container.addChild(button_51, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_28 = new cpr.controls.Output("output_f754e2ce");
					output_28.value = "버튼";
					container.addChild(output_28, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_52 = new cpr.controls.Button("instance_429397c2");
					button_52.value = "Button";
					container.addChild(button_52, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_53 = new cpr.controls.Button("instance_12aa013b");
					button_53.value = "Button";
					button_53.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_53, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_29 = new cpr.controls.Output("output_f6d62153");
					output_29.value = "버튼";
					container.addChild(output_29, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_54 = new cpr.controls.Button("instance_28cecd76");
					button_54.value = "Button";
					button_54.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_54, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_55 = new cpr.controls.Button("instance_fb3baa04");
					button_55.value = "Button";
					container.addChild(button_55, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_30 = new cpr.controls.Output("output_b9112963");
					output_30.value = "버튼";
					container.addChild(output_30, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_56 = new cpr.controls.Button("instance_39a9e019");
					button_56.value = "Button";
					container.addChild(button_56, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_57 = new cpr.controls.Button("instance_3fe32a62");
					button_57.value = "Button";
					container.addChild(button_57, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_31 = new cpr.controls.Output("output_24be6332");
					output_31.value = "버튼";
					container.addChild(output_31, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_58 = new cpr.controls.Button("instance_ac246e27");
					button_58.value = "Button";
					container.addChild(button_58, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_59 = new cpr.controls.Button("instance_72b8cd79");
					button_59.value = "Button";
					container.addChild(button_59, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_32 = new cpr.controls.Output("output_1730270a");
					output_32.value = "버튼";
					container.addChild(output_32, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_60 = new cpr.controls.Button("instance_0a43f724");
					button_60.value = "Button";
					container.addChild(button_60, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_61 = new cpr.controls.Button("instance_1e5e173f");
					button_61.value = "Button";
					button_61.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_61, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_33 = new cpr.controls.Output("output_514de107");
					output_33.value = "버튼";
					container.addChild(output_33, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_62 = new cpr.controls.Button("instance_092443ed");
					button_62.value = "Button";
					button_62.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_62, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_63 = new cpr.controls.Button("instance_033f51e9");
					button_63.value = "Button";
					container.addChild(button_63, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_34 = new cpr.controls.Output("output_1af7ecff");
					output_34.value = "버튼";
					container.addChild(output_34, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_64 = new cpr.controls.Button("instance_a60cbc82");
					button_64.value = "Button";
					container.addChild(button_64, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_65 = new cpr.controls.Button("instance_984b79f5");
					button_65.value = "Button";
					container.addChild(button_65, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_35 = new cpr.controls.Output("output_4f5ab3f4");
					output_35.value = "버튼";
					container.addChild(output_35, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_66 = new cpr.controls.Button("instance_6e606b6a");
					button_66.value = "Button";
					container.addChild(button_66, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_67 = new cpr.controls.Button("instance_51be6c30");
					button_67.value = "Button";
					container.addChild(button_67, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_36 = new cpr.controls.Output("output_d4b3d47c");
					output_36.value = "버튼";
					container.addChild(output_36, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_68 = new cpr.controls.Button("instance_1ecca0e8");
					button_68.value = "Button";
					container.addChild(button_68, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_69 = new cpr.controls.Button("instance_8c8fa00b");
					button_69.value = "Button";
					container.addChild(button_69, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_37 = new cpr.controls.Output("output_41a0dc0a");
					output_37.value = "버튼";
					container.addChild(output_37, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_70 = new cpr.controls.Button("instance_5c7230d8");
					button_70.value = "Button";
					container.addChild(button_70, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_71 = new cpr.controls.Button("instance_91a90d3b");
					button_71.value = "Button";
					container.addChild(button_71, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_38 = new cpr.controls.Output("output_29a12d98");
					output_38.value = "버튼";
					container.addChild(output_38, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_72 = new cpr.controls.Button("instance_ac6a4078");
					button_72.value = "Button";
					container.addChild(button_72, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_73 = new cpr.controls.Button("instance_8384c409");
					button_73.value = "Button";
					container.addChild(button_73, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_39 = new cpr.controls.Output("output_e14b12b9");
					output_39.value = "버튼";
					container.addChild(output_39, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_74 = new cpr.controls.Button("instance_04a9c293");
					button_74.value = "Button";
					container.addChild(button_74, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_75 = new cpr.controls.Button("instance_ae53383c");
					button_75.value = "Button";
					container.addChild(button_75, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_40 = new cpr.controls.Output("output_7edb65e5");
					output_40.value = "버튼";
					container.addChild(output_40, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_76 = new cpr.controls.Button("instance_6e0001d0");
					button_76.value = "Button";
					container.addChild(button_76, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_77 = new cpr.controls.Button("instance_6ff539cc");
					button_77.value = "Button";
					button_77.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_77, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_41 = new cpr.controls.Output("output_e22cc77d");
					output_41.value = "버튼";
					container.addChild(output_41, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_78 = new cpr.controls.Button("instance_4b1cab40");
					button_78.value = "Button";
					button_78.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_78, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_79 = new cpr.controls.Button("instance_f30e69ab");
					button_79.value = "Button";
					container.addChild(button_79, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_42 = new cpr.controls.Output("output_bd97ffd1");
					output_42.value = "버튼";
					container.addChild(output_42, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_80 = new cpr.controls.Button("instance_43548ae8");
					button_80.value = "Button";
					container.addChild(button_80, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_81 = new cpr.controls.Button("instance_49db722e");
					button_81.value = "Button";
					container.addChild(button_81, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_43 = new cpr.controls.Output("output_70f36a68");
					output_43.value = "버튼";
					container.addChild(output_43, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_82 = new cpr.controls.Button("instance_f81047c6");
					button_82.value = "Button";
					container.addChild(button_82, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_83 = new cpr.controls.Button("instance_3bbc90b3");
					button_83.value = "Button";
					button_83.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_83, {
						"top": "16.0px",
						"left": "20.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var output_44 = new cpr.controls.Output("output_9287c989");
					output_44.value = "버튼";
					container.addChild(output_44, {
						"top": "21.5px",
						"left": "20.0px",
						"width": "33.0px",
						"height": "13.0px"
					});
					var button_84 = new cpr.controls.Button("instance_c71f5716");
					button_84.value = "Button";
					button_84.style.css({
						"background-color" : "#FFFFFF",
						"background-image" : "none"
					});
					container.addChild(button_84, {
						"top": "16.0px",
						"left": "57.0px",
						"width": "24.0px",
						"height": "24.0px"
					});
					var button_85 = new cpr.controls.Button("instance_bcb827f6");
					button_85.value = "Button";
					container.addChild(button_85, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_45 = new cpr.controls.Output("output_81441f99");
					output_45.value = "버튼";
					container.addChild(output_45, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_86 = new cpr.controls.Button("instance_a3d9aee0");
					button_86.value = "Button";
					container.addChild(button_86, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_87 = new cpr.controls.Button("instance_1d36b23c");
					button_87.value = "Button";
					container.addChild(button_87, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_46 = new cpr.controls.Output("output_46b2903f");
					output_46.value = "버튼";
					container.addChild(output_46, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_88 = new cpr.controls.Button("instance_b04a76f7");
					button_88.value = "Button";
					container.addChild(button_88, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_89 = new cpr.controls.Button("instance_96e8c1d0");
					button_89.value = "Button";
					container.addChild(button_89, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_47 = new cpr.controls.Output("output_9cd3475c");
					output_47.value = "버튼";
					container.addChild(output_47, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_90 = new cpr.controls.Button("instance_7097a3d0");
					button_90.value = "Button";
					container.addChild(button_90, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var button_91 = new cpr.controls.Button("instance_e98b78be");
					button_91.value = "Button";
					container.addChild(button_91, {
						"top": "14.0px",
						"left": "16.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_48 = new cpr.controls.Output("output_7f6c79c6");
					output_48.value = "버튼";
					container.addChild(output_48, {
						"top": "18.0px",
						"left": "16.0px",
						"width": "30.0px",
						"height": "12.0px"
					});
					var button_92 = new cpr.controls.Button("instance_56957770");
					button_92.value = "Button";
					container.addChild(button_92, {
						"top": "14.0px",
						"left": "50.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_93 = new cpr.controls.Button("instance_ba645223");
					button_93.value = "Button";
					container.addChild(button_93, {
						"top": "10.0px",
						"left": "12.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var output_49 = new cpr.controls.Output("output_6b085bdd");
					output_49.value = "버튼";
					container.addChild(output_49, {
						"top": "14.5px",
						"left": "12.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_94 = new cpr.controls.Button("instance_927ea6bd");
					button_94.value = "Button";
					container.addChild(button_94, {
						"top": "10.0px",
						"left": "42.0px",
						"width": "20.0px",
						"height": "20.0px"
					});
					var button_95 = new cpr.controls.Button("instance_7580d04f");
					button_95.value = "Button";
					container.addChild(button_95, {
						"top": "8.0px",
						"left": "10.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
					var output_50 = new cpr.controls.Output("output_723861e3");
					output_50.value = "버튼";
					container.addChild(output_50, {
						"top": "10.5px",
						"left": "10.0px",
						"width": "26.0px",
						"height": "11.0px"
					});
					var button_96 = new cpr.controls.Button("instance_62485b9f");
					button_96.value = "Button";
					container.addChild(button_96, {
						"top": "8.0px",
						"left": "40.0px",
						"width": "16.0px",
						"height": "16.0px"
					});
				})(group_3);
				container.addChild(group_3, {
					"top": "280.0px",
					"left": "110.0px",
					"width": "1700.0px",
					"height": "1307.0px"
				});
				var group_4 = new cpr.controls.Container("group_d912437b");
				var xYLayout_5 = new cpr.controls.layouts.XYLayout();
				group_4.setLayout(xYLayout_5);
				(function(container){
					var group_5 = new cpr.controls.Container("group_762b0712");
					var xYLayout_6 = new cpr.controls.layouts.XYLayout();
					group_5.setLayout(xYLayout_6);
					(function(container){
						var group_6 = new cpr.controls.Container("group_f55ac8b0");
						group_6.style.css({
							"background-color" : "#FFFFFF",
							"border-bottom-color" : "#e0f0ff",
							"border-left-color" : "#e0f0ff",
							"border-top-color" : "#e0f0ff",
							"border-right-color" : "#e0f0ff"
						});
						var xYLayout_7 = new cpr.controls.layouts.XYLayout();
						group_6.setLayout(xYLayout_7);
						(function(container){
							var output_51 = new cpr.controls.Output("output_3c0a0f97");
							output_51.value = "100";
							container.addChild(output_51, {
								"top": "16.0px",
								"left": "36.0px",
								"width": "28.0px",
								"height": "20.0px"
							});
							var output_52 = new cpr.controls.Output("output_7ad79273");
							output_52.value = "#ffffff";
							container.addChild(output_52, {
								"top": "66.0px",
								"left": "18.0px",
								"width": "64.0px",
								"height": "18.0px"
							});
						})(group_6);
						container.addChild(group_6, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_7 = new cpr.controls.Container("group_729b8bdd");
						group_7.style.css({
							"background-color" : "#E7F3FF"
						});
						var xYLayout_8 = new cpr.controls.layouts.XYLayout();
						group_7.setLayout(xYLayout_8);
						(function(container){
							var output_53 = new cpr.controls.Output("output_14f6053c");
							output_53.value = "95";
							container.addChild(output_53, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_54 = new cpr.controls.Output("output_9988ca9c");
							output_54.value = "#E0F0FF";
							container.addChild(output_54, {
								"top": "66.0px",
								"left": "17.5px",
								"width": "65.0px",
								"height": "18.0px"
							});
						})(group_7);
						container.addChild(group_7, {
							"top": "0.0px",
							"left": "100.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_8 = new cpr.controls.Container("group_a7a0f605");
						group_8.style.css({
							"background-color" : "#C6E3FF"
						});
						var xYLayout_9 = new cpr.controls.layouts.XYLayout();
						group_8.setLayout(xYLayout_9);
						(function(container){
							var output_55 = new cpr.controls.Output("output_22e9feca");
							output_55.value = "90";
							container.addChild(output_55, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_56 = new cpr.controls.Output("output_2fa7ea45");
							output_56.value = "#C7E4FF";
							container.addChild(output_56, {
								"top": "66.0px",
								"left": "16.5px",
								"width": "67.0px",
								"height": "18.0px"
							});
						})(group_8);
						container.addChild(group_8, {
							"top": "0.0px",
							"left": "200.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_9 = new cpr.controls.Container("group_df533657");
						group_9.style.css({
							"background-color" : "#ADD7FF"
						});
						var xYLayout_10 = new cpr.controls.layouts.XYLayout();
						group_9.setLayout(xYLayout_10);
						(function(container){
							var output_57 = new cpr.controls.Output("output_1237ddc1");
							output_57.value = "80";
							container.addChild(output_57, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_58 = new cpr.controls.Output("output_57177260");
							output_58.value = "#ADD8FF";
							container.addChild(output_58, {
								"top": "66.0px",
								"left": "15.5px",
								"width": "69.0px",
								"height": "18.0px"
							});
						})(group_9);
						container.addChild(group_9, {
							"top": "0.0px",
							"left": "300.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_10 = new cpr.controls.Container("group_65d0f570");
						group_10.style.css({
							"background-color" : "#7ABFFF"
						});
						var xYLayout_11 = new cpr.controls.layouts.XYLayout();
						group_10.setLayout(xYLayout_11);
						(function(container){
							var output_59 = new cpr.controls.Output("output_90e5318a");
							output_59.value = "70";
							container.addChild(output_59, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_60 = new cpr.controls.Output("output_d290c98d");
							output_60.value = "#0075E0";
							container.addChild(output_60, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_10);
						container.addChild(group_10, {
							"top": "0.0px",
							"left": "400.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_11 = new cpr.controls.Container("group_b9c2479a");
						group_11.style.css({
							"background-color" : "#148EFF"
						});
						var xYLayout_12 = new cpr.controls.layouts.XYLayout();
						group_11.setLayout(xYLayout_12);
						(function(container){
							var output_61 = new cpr.controls.Output("output_a3cb47a0");
							output_61.value = "60";
							container.addChild(output_61, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_62 = new cpr.controls.Output("output_8995e291");
							output_62.value = "#148EFF";
							container.addChild(output_62, {
								"top": "66.0px",
								"left": "17.5px",
								"width": "65.0px",
								"height": "18.0px"
							});
						})(group_11);
						container.addChild(group_11, {
							"top": "0.0px",
							"left": "500.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_12 = new cpr.controls.Container("group_0add14ca");
						group_12.style.css({
							"background-color" : "#0074E0"
						});
						var xYLayout_13 = new cpr.controls.layouts.XYLayout();
						group_12.setLayout(xYLayout_13);
						(function(container){
							var output_63 = new cpr.controls.Output("output_90b64656");
							output_63.value = "50";
							container.addChild(output_63, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_64 = new cpr.controls.Output("output_4d21bdc2");
							output_64.value = "#0075E0";
							container.addChild(output_64, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_12);
						container.addChild(group_12, {
							"top": "0.0px",
							"left": "600.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_13 = new cpr.controls.Container("group_c2816202");
						group_13.style.css({
							"background-color" : "#0067C6"
						});
						var xYLayout_14 = new cpr.controls.layouts.XYLayout();
						group_13.setLayout(xYLayout_14);
						(function(container){
							var output_65 = new cpr.controls.Output("output_63715c07");
							output_65.value = "40";
							container.addChild(output_65, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_66 = new cpr.controls.Output("output_87486651");
							output_66.value = "#0067C7";
							container.addChild(output_66, {
								"top": "66.0px",
								"left": "16.5px",
								"width": "67.0px",
								"height": "18.0px"
							});
						})(group_13);
						container.addChild(group_13, {
							"top": "0.0px",
							"left": "700.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_14 = new cpr.controls.Container("group_00d9c3c0");
						group_14.style.css({
							"background-color" : "#004C93"
						});
						var xYLayout_15 = new cpr.controls.layouts.XYLayout();
						group_14.setLayout(xYLayout_15);
						(function(container){
							var output_67 = new cpr.controls.Output("output_01a156fc");
							output_67.value = "30";
							container.addChild(output_67, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_68 = new cpr.controls.Output("output_f7f29be6");
							output_68.value = "#004D94";
							container.addChild(output_68, {
								"top": "66.0px",
								"left": "16.5px",
								"width": "67.0px",
								"height": "18.0px"
							});
						})(group_14);
						container.addChild(group_14, {
							"top": "0.0px",
							"left": "800.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_15 = new cpr.controls.Container("group_0f6a7b47");
						group_15.style.css({
							"background-color" : "#003261"
						});
						var xYLayout_16 = new cpr.controls.layouts.XYLayout();
						group_15.setLayout(xYLayout_16);
						(function(container){
							var output_69 = new cpr.controls.Output("output_472934e3");
							output_69.value = "20";
							container.addChild(output_69, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_70 = new cpr.controls.Output("output_390b7db4");
							output_70.value = "#003261";
							container.addChild(output_70, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_15);
						container.addChild(group_15, {
							"top": "0.0px",
							"left": "900.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_16 = new cpr.controls.Container("group_74d093f5");
						group_16.style.css({
							"background-color" : "#00172D"
						});
						var xYLayout_17 = new cpr.controls.layouts.XYLayout();
						group_16.setLayout(xYLayout_17);
						(function(container){
							var output_71 = new cpr.controls.Output("output_645dc22b");
							output_71.value = "10";
							container.addChild(output_71, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_72 = new cpr.controls.Output("output_b7605a23");
							output_72.value = "#00182E";
							container.addChild(output_72, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_16);
						container.addChild(group_16, {
							"top": "0.0px",
							"left": "1000.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_17 = new cpr.controls.Container("group_ce794954");
						group_17.style.css({
							"background-color" : "#000000"
						});
						var xYLayout_18 = new cpr.controls.layouts.XYLayout();
						group_17.setLayout(xYLayout_18);
						(function(container){
							var output_73 = new cpr.controls.Output("output_3989e08f");
							output_73.value = "0";
							container.addChild(output_73, {
								"top": "16.0px",
								"left": "45.0px",
								"width": "10.0px",
								"height": "20.0px"
							});
							var output_74 = new cpr.controls.Output("output_cf47625b");
							output_74.value = "#000000";
							container.addChild(output_74, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_17);
						container.addChild(group_17, {
							"top": "0.0px",
							"left": "1100.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
					})(group_5);
					container.addChild(group_5, {
						"top": "280.0px",
						"left": "149.84912109375px",
						"width": "1200.0px",
						"height": "100.0px"
					});
					var group_18 = new cpr.controls.Container("group_76fac7ca");
					var xYLayout_19 = new cpr.controls.layouts.XYLayout();
					group_18.setLayout(xYLayout_19);
					(function(container){
						var group_19 = new cpr.controls.Container("group_7576f300");
						group_19.style.css({
							"background-color" : "#FFFFFF"
						});
						var xYLayout_20 = new cpr.controls.layouts.XYLayout();
						group_19.setLayout(xYLayout_20);
						(function(container){
							var output_75 = new cpr.controls.Output("output_8b91c7af");
							output_75.value = "0";
							container.addChild(output_75, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "10.0px",
								"height": "12.0px"
							});
							var output_76 = new cpr.controls.Output("output_f6170058");
							output_76.value = "#FFFFFF";
							container.addChild(output_76, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "52.0px",
								"height": "9.0px"
							});
						})(group_19);
						container.addChild(group_19, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_20 = new cpr.controls.Container("group_b192b005");
						group_20.style.css({
							"background-color" : "#FFFBE5"
						});
						var xYLayout_21 = new cpr.controls.layouts.XYLayout();
						group_20.setLayout(xYLayout_21);
						(function(container){
							var output_77 = new cpr.controls.Output("output_68c44e32");
							output_77.value = "5";
							container.addChild(output_77, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "10.0px",
								"height": "12.0px"
							});
							var output_78 = new cpr.controls.Output("output_d2fb1586");
							output_78.value = "#FFFBE5";
							container.addChild(output_78, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "53.0px",
								"height": "9.0px"
							});
						})(group_20);
						container.addChild(group_20, {
							"top": "0.0px",
							"left": "100.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_21 = new cpr.controls.Container("group_c8793701");
						group_21.style.css({
							"background-color" : "#FFF6CC"
						});
						var xYLayout_22 = new cpr.controls.layouts.XYLayout();
						group_21.setLayout(xYLayout_22);
						(function(container){
							var output_79 = new cpr.controls.Output("output_f00a48ee");
							output_79.value = "10";
							container.addChild(output_79, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_80 = new cpr.controls.Output("output_59fd5742");
							output_80.value = "#FFF6CC";
							container.addChild(output_80, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "56.0px",
								"height": "9.0px"
							});
						})(group_21);
						container.addChild(group_21, {
							"top": "0.0px",
							"left": "200.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_22 = new cpr.controls.Container("group_4a8fbbad");
						group_22.style.css({
							"background-color" : "#FFED99"
						});
						var xYLayout_23 = new cpr.controls.layouts.XYLayout();
						group_22.setLayout(xYLayout_23);
						(function(container){
							var output_81 = new cpr.controls.Output("output_8a59f4a3");
							output_81.value = "20";
							container.addChild(output_81, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_82 = new cpr.controls.Output("output_3fd211d5");
							output_82.value = "#FFEE99";
							container.addChild(output_82, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "52.0px",
								"height": "9.0px"
							});
						})(group_22);
						container.addChild(group_22, {
							"top": "0.0px",
							"left": "300.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_23 = new cpr.controls.Container("group_d038e029");
						group_23.style.css({
							"background-color" : "#FFE566"
						});
						var xYLayout_24 = new cpr.controls.layouts.XYLayout();
						group_23.setLayout(xYLayout_24);
						(function(container){
							var output_83 = new cpr.controls.Output("output_fe871104");
							output_83.value = "30";
							container.addChild(output_83, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_84 = new cpr.controls.Output("output_108add06");
							output_84.value = "#FFE566";
							container.addChild(output_84, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "53.0px",
								"height": "9.0px"
							});
						})(group_23);
						container.addChild(group_23, {
							"top": "0.0px",
							"left": "400.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_24 = new cpr.controls.Container("group_447a3a09");
						group_24.style.css({
							"background-color" : "#FFD048"
						});
						var xYLayout_25 = new cpr.controls.layouts.XYLayout();
						group_24.setLayout(xYLayout_25);
						(function(container){
							var output_85 = new cpr.controls.Output("output_7102146a");
							output_85.value = "40";
							container.addChild(output_85, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_86 = new cpr.controls.Output("output_f137ce81");
							output_86.value = "#FFD148";
							container.addChild(output_86, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_24);
						container.addChild(group_24, {
							"top": "0.0px",
							"left": "500.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_25 = new cpr.controls.Container("group_0418d77a");
						group_25.style.css({
							"background-color" : "#FFC20E"
						});
						var xYLayout_26 = new cpr.controls.layouts.XYLayout();
						group_25.setLayout(xYLayout_26);
						(function(container){
							var output_87 = new cpr.controls.Output("output_1ec3addc");
							output_87.value = "50";
							container.addChild(output_87, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_88 = new cpr.controls.Output("output_d74ed92b");
							output_88.value = "#FFC20E";
							container.addChild(output_88, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_25);
						container.addChild(group_25, {
							"top": "0.0px",
							"left": "600.0px",
							"width": "160.0px",
							"height": "100.0px"
						});
						var group_26 = new cpr.controls.Container("group_c64eb469");
						group_26.style.css({
							"background-color" : "#EAB20D"
						});
						var xYLayout_27 = new cpr.controls.layouts.XYLayout();
						group_26.setLayout(xYLayout_27);
						(function(container){
							var output_89 = new cpr.controls.Output("output_17baebd0");
							output_89.value = "60";
							container.addChild(output_89, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_90 = new cpr.controls.Output("output_93e7cdeb");
							output_90.value = "#EBB30E";
							container.addChild(output_90, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_26);
						container.addChild(group_26, {
							"top": "0.0px",
							"left": "760.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_27 = new cpr.controls.Container("group_d53b5b38");
						group_27.style.css({
							"background-color" : "#C89704"
						});
						var xYLayout_28 = new cpr.controls.layouts.XYLayout();
						group_27.setLayout(xYLayout_28);
						(function(container){
							var output_91 = new cpr.controls.Output("output_2da225ad");
							output_91.value = "70";
							container.addChild(output_91, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_92 = new cpr.controls.Output("output_bc351d0a");
							output_92.value = "#C99704";
							container.addChild(output_92, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "55.0px",
								"height": "9.0px"
							});
						})(group_27);
						container.addChild(group_27, {
							"top": "0.0px",
							"left": "860.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_28 = new cpr.controls.Container("group_3e6f7682");
						group_28.style.css({
							"background-color" : "#69510B"
						});
						var xYLayout_29 = new cpr.controls.layouts.XYLayout();
						group_28.setLayout(xYLayout_29);
						(function(container){
							var output_93 = new cpr.controls.Output("output_2bbebe8e");
							output_93.value = "80";
							container.addChild(output_93, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_94 = new cpr.controls.Output("output_7e8cc90c");
							output_94.value = "#69510B";
							container.addChild(output_94, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_28);
						container.addChild(group_28, {
							"top": "0.0px",
							"left": "960.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_29 = new cpr.controls.Container("group_048e390f");
						group_29.style.css({
							"background-color" : "#332A00"
						});
						var xYLayout_30 = new cpr.controls.layouts.XYLayout();
						group_29.setLayout(xYLayout_30);
						(function(container){
							var output_95 = new cpr.controls.Output("output_daa147b3");
							output_95.value = "90";
							container.addChild(output_95, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_96 = new cpr.controls.Output("output_a9a4535f");
							output_96.value = "#332A00";
							container.addChild(output_96, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_29);
						container.addChild(group_29, {
							"top": "0.0px",
							"left": "1060.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_30 = new cpr.controls.Container("group_7040e914");
						group_30.style.css({
							"background-color" : "#000000"
						});
						var xYLayout_31 = new cpr.controls.layouts.XYLayout();
						group_30.setLayout(xYLayout_31);
						(function(container){
							var output_97 = new cpr.controls.Output("output_8417a9b1");
							output_97.value = "100";
							container.addChild(output_97, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "30.0px",
								"height": "12.0px"
							});
							var output_98 = new cpr.controls.Output("output_4776c7f3");
							output_98.value = "#000000";
							container.addChild(output_98, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "53.0px",
								"height": "9.0px"
							});
						})(group_30);
						container.addChild(group_30, {
							"top": "0.0px",
							"left": "1160.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
					})(group_18);
					container.addChild(group_18, {
						"top": "90.0px",
						"left": "0.0px",
						"width": "1260.0px",
						"height": "100.0px"
					});
					var group_31 = new cpr.controls.Container("group_ecc8b9cf");
					group_31.style.css({
						"background-color" : "#0074E0",
						"border-bottom-color" : "#000000",
						"border-left-color" : "#000000",
						"border-top-color" : "#000000",
						"border-right-color" : "#000000"
					});
					var xYLayout_32 = new cpr.controls.layouts.XYLayout();
					group_31.setLayout(xYLayout_32);
					(function(container){
						var output_99 = new cpr.controls.Output("output_bfff1b30");
						output_99.value = "3 : 1 (With white)";
						container.addChild(output_99, {
							"top": "10.0px",
							"left": "314.5px",
							"width": "131.0px",
							"height": "12.0px"
						});
					})(group_31);
					container.addChild(group_31, {
						"top": "0.0px",
						"left": "500.0px",
						"width": "760.0px",
						"height": "90.0px"
					});
					var group_32 = new cpr.controls.Container("group_de55685a");
					group_32.style.css({
						"background-color" : "#0074E0",
						"border-bottom-color" : "#000000",
						"border-left-color" : "#000000",
						"border-top-color" : "#000000",
						"border-right-color" : "#000000"
					});
					var xYLayout_33 = new cpr.controls.layouts.XYLayout();
					group_32.setLayout(xYLayout_33);
					(function(container){
						var output_100 = new cpr.controls.Output("output_ca4f4eff");
						output_100.value = "4.5 : 1 (With white)";
						container.addChild(output_100, {
							"top": "10.0px",
							"left": "258.0px",
							"width": "145.0px",
							"height": "12.0px"
						});
					})(group_32);
					container.addChild(group_32, {
						"top": "50.0px",
						"left": "599.0px",
						"width": "661.0px",
						"height": "40.0px"
					});
					var output_101 = new cpr.controls.Output("output_ea853b9e");
					output_101.value = "Tints";
					container.addChild(output_101, {
						"top": "247.0px",
						"left": "563.0px",
						"width": "38.0px",
						"height": "12.0px"
					});
					var output_102 = new cpr.controls.Output("output_1639dad5");
					output_102.value = "Base";
					container.addChild(output_102, {
						"top": "247.0px",
						"left": "663.0px",
						"width": "38.0px",
						"height": "12.0px"
					});
					var output_103 = new cpr.controls.Output("output_5fbc795c");
					output_103.value = "Shades";
					container.addChild(output_103, {
						"top": "247.0px",
						"left": "760.0px",
						"width": "57.0px",
						"height": "12.0px"
					});
				})(group_4);
				container.addChild(group_4, {
					"top": "1747.0px",
					"left": "330.0px",
					"width": "1260.0px",
					"height": "259.0px"
				});
				var group_33 = new cpr.controls.Container("group_830a7bcc");
				var xYLayout_34 = new cpr.controls.layouts.XYLayout();
				group_33.setLayout(xYLayout_34);
				(function(container){
					var group_34 = new cpr.controls.Container("group_52069bbf");
					var xYLayout_35 = new cpr.controls.layouts.XYLayout();
					group_34.setLayout(xYLayout_35);
					(function(container){
						var group_35 = new cpr.controls.Container("group_229afe3e");
						group_35.style.css({
							"background-color" : "#FFFFFF",
							"border-bottom-color" : "#e0f0ff",
							"border-left-color" : "#e0f0ff",
							"border-top-color" : "#e0f0ff",
							"border-right-color" : "#e0f0ff"
						});
						var xYLayout_36 = new cpr.controls.layouts.XYLayout();
						group_35.setLayout(xYLayout_36);
						(function(container){
							var output_104 = new cpr.controls.Output("output_a1298793");
							output_104.value = "100";
							container.addChild(output_104, {
								"top": "16.0px",
								"left": "36.0px",
								"width": "28.0px",
								"height": "20.0px"
							});
							var output_105 = new cpr.controls.Output("output_1e9916db");
							output_105.value = "#ffffff";
							container.addChild(output_105, {
								"top": "66.0px",
								"left": "18.0px",
								"width": "64.0px",
								"height": "18.0px"
							});
						})(group_35);
						container.addChild(group_35, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_36 = new cpr.controls.Container("group_f9ceddbc");
						group_36.style.css({
							"background-color" : "#E7F3FF"
						});
						var xYLayout_37 = new cpr.controls.layouts.XYLayout();
						group_36.setLayout(xYLayout_37);
						(function(container){
							var output_106 = new cpr.controls.Output("output_4085cb14");
							output_106.value = "95";
							container.addChild(output_106, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_107 = new cpr.controls.Output("output_0e2b1339");
							output_107.value = "#E0F0FF";
							container.addChild(output_107, {
								"top": "66.0px",
								"left": "17.5px",
								"width": "65.0px",
								"height": "18.0px"
							});
						})(group_36);
						container.addChild(group_36, {
							"top": "0.0px",
							"left": "100.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_37 = new cpr.controls.Container("group_61646243");
						group_37.style.css({
							"background-color" : "#C6E3FF"
						});
						var xYLayout_38 = new cpr.controls.layouts.XYLayout();
						group_37.setLayout(xYLayout_38);
						(function(container){
							var output_108 = new cpr.controls.Output("output_c59e61ec");
							output_108.value = "90";
							container.addChild(output_108, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_109 = new cpr.controls.Output("output_cc11a3a5");
							output_109.value = "#C7E4FF";
							container.addChild(output_109, {
								"top": "66.0px",
								"left": "16.5px",
								"width": "67.0px",
								"height": "18.0px"
							});
						})(group_37);
						container.addChild(group_37, {
							"top": "0.0px",
							"left": "200.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_38 = new cpr.controls.Container("group_f3a594fb");
						group_38.style.css({
							"background-color" : "#ADD7FF"
						});
						var xYLayout_39 = new cpr.controls.layouts.XYLayout();
						group_38.setLayout(xYLayout_39);
						(function(container){
							var output_110 = new cpr.controls.Output("output_ed107a23");
							output_110.value = "80";
							container.addChild(output_110, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_111 = new cpr.controls.Output("output_190cb67b");
							output_111.value = "#ADD8FF";
							container.addChild(output_111, {
								"top": "66.0px",
								"left": "15.5px",
								"width": "69.0px",
								"height": "18.0px"
							});
						})(group_38);
						container.addChild(group_38, {
							"top": "0.0px",
							"left": "300.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_39 = new cpr.controls.Container("group_8449b050");
						group_39.style.css({
							"background-color" : "#7ABFFF"
						});
						var xYLayout_40 = new cpr.controls.layouts.XYLayout();
						group_39.setLayout(xYLayout_40);
						(function(container){
							var output_112 = new cpr.controls.Output("output_120d606b");
							output_112.value = "70";
							container.addChild(output_112, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_113 = new cpr.controls.Output("output_ef48cff3");
							output_113.value = "#0075E0";
							container.addChild(output_113, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_39);
						container.addChild(group_39, {
							"top": "0.0px",
							"left": "400.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_40 = new cpr.controls.Container("group_c7095a55");
						group_40.style.css({
							"background-color" : "#148EFF"
						});
						var xYLayout_41 = new cpr.controls.layouts.XYLayout();
						group_40.setLayout(xYLayout_41);
						(function(container){
							var output_114 = new cpr.controls.Output("output_91e42528");
							output_114.value = "60";
							container.addChild(output_114, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_115 = new cpr.controls.Output("output_aaac42a7");
							output_115.value = "#148EFF";
							container.addChild(output_115, {
								"top": "66.0px",
								"left": "17.5px",
								"width": "65.0px",
								"height": "18.0px"
							});
						})(group_40);
						container.addChild(group_40, {
							"top": "0.0px",
							"left": "500.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_41 = new cpr.controls.Container("group_9b5dd609");
						group_41.style.css({
							"background-color" : "#0074E0"
						});
						var xYLayout_42 = new cpr.controls.layouts.XYLayout();
						group_41.setLayout(xYLayout_42);
						(function(container){
							var output_116 = new cpr.controls.Output("output_9d18e8f2");
							output_116.value = "50";
							container.addChild(output_116, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_117 = new cpr.controls.Output("output_de3ff172");
							output_117.value = "#0075E0";
							container.addChild(output_117, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_41);
						container.addChild(group_41, {
							"top": "0.0px",
							"left": "600.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_42 = new cpr.controls.Container("group_1551ee5c");
						group_42.style.css({
							"background-color" : "#0067C6"
						});
						var xYLayout_43 = new cpr.controls.layouts.XYLayout();
						group_42.setLayout(xYLayout_43);
						(function(container){
							var output_118 = new cpr.controls.Output("output_2f8d3274");
							output_118.value = "40";
							container.addChild(output_118, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_119 = new cpr.controls.Output("output_1cc9ae4f");
							output_119.value = "#0067C7";
							container.addChild(output_119, {
								"top": "66.0px",
								"left": "16.5px",
								"width": "67.0px",
								"height": "18.0px"
							});
						})(group_42);
						container.addChild(group_42, {
							"top": "0.0px",
							"left": "700.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_43 = new cpr.controls.Container("group_58c1a389");
						group_43.style.css({
							"background-color" : "#004C93"
						});
						var xYLayout_44 = new cpr.controls.layouts.XYLayout();
						group_43.setLayout(xYLayout_44);
						(function(container){
							var output_120 = new cpr.controls.Output("output_650fdf95");
							output_120.value = "30";
							container.addChild(output_120, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_121 = new cpr.controls.Output("output_b96e8e1e");
							output_121.value = "#004D94";
							container.addChild(output_121, {
								"top": "66.0px",
								"left": "16.5px",
								"width": "67.0px",
								"height": "18.0px"
							});
						})(group_43);
						container.addChild(group_43, {
							"top": "0.0px",
							"left": "800.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_44 = new cpr.controls.Container("group_036fcb3f");
						group_44.style.css({
							"background-color" : "#003261"
						});
						var xYLayout_45 = new cpr.controls.layouts.XYLayout();
						group_44.setLayout(xYLayout_45);
						(function(container){
							var output_122 = new cpr.controls.Output("output_b6187b55");
							output_122.value = "20";
							container.addChild(output_122, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_123 = new cpr.controls.Output("output_ce85c342");
							output_123.value = "#003261";
							container.addChild(output_123, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_44);
						container.addChild(group_44, {
							"top": "0.0px",
							"left": "900.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_45 = new cpr.controls.Container("group_4ff17dfc");
						group_45.style.css({
							"background-color" : "#00172D"
						});
						var xYLayout_46 = new cpr.controls.layouts.XYLayout();
						group_45.setLayout(xYLayout_46);
						(function(container){
							var output_124 = new cpr.controls.Output("output_98e27394");
							output_124.value = "10";
							container.addChild(output_124, {
								"top": "16.0px",
								"left": "40.5px",
								"width": "19.0px",
								"height": "20.0px"
							});
							var output_125 = new cpr.controls.Output("output_637aeb6f");
							output_125.value = "#00182E";
							container.addChild(output_125, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_45);
						container.addChild(group_45, {
							"top": "0.0px",
							"left": "1000.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_46 = new cpr.controls.Container("group_b491b551");
						group_46.style.css({
							"background-color" : "#000000"
						});
						var xYLayout_47 = new cpr.controls.layouts.XYLayout();
						group_46.setLayout(xYLayout_47);
						(function(container){
							var output_126 = new cpr.controls.Output("output_9c0e6914");
							output_126.value = "0";
							container.addChild(output_126, {
								"top": "16.0px",
								"left": "45.0px",
								"width": "10.0px",
								"height": "20.0px"
							});
							var output_127 = new cpr.controls.Output("output_3e63c046");
							output_127.value = "#000000";
							container.addChild(output_127, {
								"top": "66.0px",
								"left": "17.0px",
								"width": "66.0px",
								"height": "18.0px"
							});
						})(group_46);
						container.addChild(group_46, {
							"top": "0.0px",
							"left": "1100.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
					})(group_34);
					container.addChild(group_34, {
						"top": "280.0px",
						"left": "149.84912109375px",
						"width": "1200.0px",
						"height": "100.0px"
					});
					var group_47 = new cpr.controls.Container("group_70de2db7");
					var xYLayout_48 = new cpr.controls.layouts.XYLayout();
					group_47.setLayout(xYLayout_48);
					(function(container){
						var group_48 = new cpr.controls.Container("group_2c10a1bd");
						group_48.style.css({
							"background-color" : "#FFFFFF"
						});
						var xYLayout_49 = new cpr.controls.layouts.XYLayout();
						group_48.setLayout(xYLayout_49);
						(function(container){
							var output_128 = new cpr.controls.Output("output_3b88f594");
							output_128.value = "0";
							container.addChild(output_128, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "10.0px",
								"height": "12.0px"
							});
							var output_129 = new cpr.controls.Output("output_1b51ae64");
							output_129.value = "#FFFFFF";
							container.addChild(output_129, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "52.0px",
								"height": "9.0px"
							});
						})(group_48);
						container.addChild(group_48, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_49 = new cpr.controls.Container("group_2ecb1b7c");
						group_49.style.css({
							"background-color" : "#FFFBE5"
						});
						var xYLayout_50 = new cpr.controls.layouts.XYLayout();
						group_49.setLayout(xYLayout_50);
						(function(container){
							var output_130 = new cpr.controls.Output("output_6ff81cff");
							output_130.value = "5";
							container.addChild(output_130, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "10.0px",
								"height": "12.0px"
							});
							var output_131 = new cpr.controls.Output("output_4dd7cd6a");
							output_131.value = "#FFFBE5";
							container.addChild(output_131, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "53.0px",
								"height": "9.0px"
							});
						})(group_49);
						container.addChild(group_49, {
							"top": "0.0px",
							"left": "100.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_50 = new cpr.controls.Container("group_92419e60");
						group_50.style.css({
							"background-color" : "#FFF6CC"
						});
						var xYLayout_51 = new cpr.controls.layouts.XYLayout();
						group_50.setLayout(xYLayout_51);
						(function(container){
							var output_132 = new cpr.controls.Output("output_e338377c");
							output_132.value = "10";
							container.addChild(output_132, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_133 = new cpr.controls.Output("output_db2b6559");
							output_133.value = "#FFF6CC";
							container.addChild(output_133, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "56.0px",
								"height": "9.0px"
							});
						})(group_50);
						container.addChild(group_50, {
							"top": "0.0px",
							"left": "200.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_51 = new cpr.controls.Container("group_061b6298");
						group_51.style.css({
							"background-color" : "#FFED99"
						});
						var xYLayout_52 = new cpr.controls.layouts.XYLayout();
						group_51.setLayout(xYLayout_52);
						(function(container){
							var output_134 = new cpr.controls.Output("output_198e7b53");
							output_134.value = "20";
							container.addChild(output_134, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_135 = new cpr.controls.Output("output_520db2de");
							output_135.value = "#FFEE99";
							container.addChild(output_135, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "52.0px",
								"height": "9.0px"
							});
						})(group_51);
						container.addChild(group_51, {
							"top": "0.0px",
							"left": "300.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_52 = new cpr.controls.Container("group_9248f1e4");
						group_52.style.css({
							"background-color" : "#FFE566"
						});
						var xYLayout_53 = new cpr.controls.layouts.XYLayout();
						group_52.setLayout(xYLayout_53);
						(function(container){
							var output_136 = new cpr.controls.Output("output_5bd2d7ed");
							output_136.value = "30";
							container.addChild(output_136, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_137 = new cpr.controls.Output("output_2adfc570");
							output_137.value = "#FFE566";
							container.addChild(output_137, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "53.0px",
								"height": "9.0px"
							});
						})(group_52);
						container.addChild(group_52, {
							"top": "0.0px",
							"left": "400.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_53 = new cpr.controls.Container("group_b3fc70aa");
						group_53.style.css({
							"background-color" : "#FFD048"
						});
						var xYLayout_54 = new cpr.controls.layouts.XYLayout();
						group_53.setLayout(xYLayout_54);
						(function(container){
							var output_138 = new cpr.controls.Output("output_b30ce5ee");
							output_138.value = "40";
							container.addChild(output_138, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_139 = new cpr.controls.Output("output_67c7b218");
							output_139.value = "#FFD148";
							container.addChild(output_139, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_53);
						container.addChild(group_53, {
							"top": "0.0px",
							"left": "500.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_54 = new cpr.controls.Container("group_4bc451ac");
						group_54.style.css({
							"background-color" : "#FFC20E"
						});
						var xYLayout_55 = new cpr.controls.layouts.XYLayout();
						group_54.setLayout(xYLayout_55);
						(function(container){
							var output_140 = new cpr.controls.Output("output_3aa9b759");
							output_140.value = "50";
							container.addChild(output_140, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_141 = new cpr.controls.Output("output_fbbc4948");
							output_141.value = "#FFC20E";
							container.addChild(output_141, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_54);
						container.addChild(group_54, {
							"top": "0.0px",
							"left": "600.0px",
							"width": "160.0px",
							"height": "100.0px"
						});
						var group_55 = new cpr.controls.Container("group_bc5a8229");
						group_55.style.css({
							"background-color" : "#E29300"
						});
						var xYLayout_56 = new cpr.controls.layouts.XYLayout();
						group_55.setLayout(xYLayout_56);
						(function(container){
							var output_142 = new cpr.controls.Output("output_a8aa8543");
							output_142.value = "60";
							container.addChild(output_142, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_143 = new cpr.controls.Output("output_38af8fce");
							output_143.value = "#E29300";
							container.addChild(output_143, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "53.0px",
								"height": "9.0px"
							});
						})(group_55);
						container.addChild(group_55, {
							"top": "0.0px",
							"left": "760.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_56 = new cpr.controls.Container("group_c4fcfa53");
						group_56.style.css({
							"background-color" : "#BB6802"
						});
						var xYLayout_57 = new cpr.controls.layouts.XYLayout();
						group_56.setLayout(xYLayout_57);
						(function(container){
							var output_144 = new cpr.controls.Output("output_f9de1bc8");
							output_144.value = "70";
							container.addChild(output_144, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_145 = new cpr.controls.Output("output_5c4bd199");
							output_145.value = "#BB6802";
							container.addChild(output_145, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_56);
						container.addChild(group_56, {
							"top": "0.0px",
							"left": "860.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_57 = new cpr.controls.Container("group_dce47c24");
						group_57.style.css({
							"background-color" : "#69510B"
						});
						var xYLayout_58 = new cpr.controls.layouts.XYLayout();
						group_57.setLayout(xYLayout_58);
						(function(container){
							var output_146 = new cpr.controls.Output("output_2e13cc61");
							output_146.value = "80";
							container.addChild(output_146, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_147 = new cpr.controls.Output("output_dd9749f2");
							output_147.value = "#69510B";
							container.addChild(output_147, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_57);
						container.addChild(group_57, {
							"top": "0.0px",
							"left": "960.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_58 = new cpr.controls.Container("group_a0336ad6");
						group_58.style.css({
							"background-color" : "#332A00"
						});
						var xYLayout_59 = new cpr.controls.layouts.XYLayout();
						group_58.setLayout(xYLayout_59);
						(function(container){
							var output_148 = new cpr.controls.Output("output_18c6c57d");
							output_148.value = "90";
							container.addChild(output_148, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "20.0px",
								"height": "12.0px"
							});
							var output_149 = new cpr.controls.Output("output_02f24d32");
							output_149.value = "#332A00";
							container.addChild(output_149, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "54.0px",
								"height": "9.0px"
							});
						})(group_58);
						container.addChild(group_58, {
							"top": "0.0px",
							"left": "1060.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
						var group_59 = new cpr.controls.Container("group_e0c5f53b");
						group_59.style.css({
							"background-color" : "#000000"
						});
						var xYLayout_60 = new cpr.controls.layouts.XYLayout();
						group_59.setLayout(xYLayout_60);
						(function(container){
							var output_150 = new cpr.controls.Output("output_06bf8c0a");
							output_150.value = "100";
							container.addChild(output_150, {
								"top": "16.0px",
								"left": "16.0px",
								"width": "30.0px",
								"height": "12.0px"
							});
							var output_151 = new cpr.controls.Output("output_be8a70f2");
							output_151.value = "#000000";
							container.addChild(output_151, {
								"top": "75.0px",
								"left": "16.0px",
								"width": "53.0px",
								"height": "9.0px"
							});
						})(group_59);
						container.addChild(group_59, {
							"top": "0.0px",
							"left": "1160.0px",
							"width": "100.0px",
							"height": "100.0px"
						});
					})(group_47);
					container.addChild(group_47, {
						"top": "90.0px",
						"left": "0.0px",
						"width": "1260.0px",
						"height": "100.0px"
					});
					var group_60 = new cpr.controls.Container("group_bd4e9692");
					group_60.style.css({
						"background-color" : "#0074E0",
						"border-bottom-color" : "#000000",
						"border-left-color" : "#000000",
						"border-top-color" : "#000000",
						"border-right-color" : "#000000"
					});
					var xYLayout_61 = new cpr.controls.layouts.XYLayout();
					group_60.setLayout(xYLayout_61);
					(function(container){
						var output_152 = new cpr.controls.Output("output_0369a982");
						output_152.value = "3 : 1 (With white)";
						container.addChild(output_152, {
							"top": "10.0px",
							"left": "314.5px",
							"width": "131.0px",
							"height": "12.0px"
						});
					})(group_60);
					container.addChild(group_60, {
						"top": "0.0px",
						"left": "500.0px",
						"width": "760.0px",
						"height": "90.0px"
					});
					var group_61 = new cpr.controls.Container("group_7611f7c2");
					group_61.style.css({
						"background-color" : "#0074E0",
						"border-bottom-color" : "#000000",
						"border-left-color" : "#000000",
						"border-top-color" : "#000000",
						"border-right-color" : "#000000"
					});
					var xYLayout_62 = new cpr.controls.layouts.XYLayout();
					group_61.setLayout(xYLayout_62);
					(function(container){
						var output_153 = new cpr.controls.Output("output_927297c7");
						output_153.value = "4.5 : 1 (With white)";
						container.addChild(output_153, {
							"top": "10.0px",
							"left": "258.0px",
							"width": "145.0px",
							"height": "12.0px"
						});
					})(group_61);
					container.addChild(group_61, {
						"top": "50.0px",
						"left": "599.0px",
						"width": "661.0px",
						"height": "40.0px"
					});
					var output_154 = new cpr.controls.Output("output_61b709b2");
					output_154.value = "Tints";
					container.addChild(output_154, {
						"top": "247.0px",
						"left": "563.0px",
						"width": "38.0px",
						"height": "12.0px"
					});
					var output_155 = new cpr.controls.Output("output_79bb8ef4");
					output_155.value = "Base";
					container.addChild(output_155, {
						"top": "247.0px",
						"left": "663.0px",
						"width": "38.0px",
						"height": "12.0px"
					});
					var output_156 = new cpr.controls.Output("output_bbb2bb2d");
					output_156.value = "Shades";
					container.addChild(output_156, {
						"top": "247.0px",
						"left": "760.0px",
						"width": "57.0px",
						"height": "12.0px"
					});
				})(group_33);
				container.addChild(group_33, {
					"top": "2086.0px",
					"left": "330.0px",
					"width": "1260.0px",
					"height": "259.0px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0.0px",
				"left": "0.0px",
				"width": "1920.0px",
				"height": "2545.0px"
			});
		}
	});
	app.title = "design72167";
	cpr.core.Platform.INSTANCE.register(app);
})();
