/*
 * App URI: 2025-04-04/design56828
 * Source Location: 2025-04-04/design56828.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5542), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("2025-04-04/design56828", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// Generated JavaScript File for design56828.clx
			console.log('JavaScript for design56828 loaded.');;
			// End - User Script
			
			// Header
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("group_5670d2ed");
			group_1.style.css({
				"background-color" : "#FFFFFF"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container("group_7314c10b");
				var xYLayout_3 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_3);
				container.addChild(group_2, {
					"top": "335.0px",
					"left": "954.0px",
					"width": "1.0px",
					"height": "354.0px"
				});
				var group_3 = new cpr.controls.Container("group_2db5b108");
				group_3.style.css({
					"background-color" : "#00ABB3"
				});
				var xYLayout_4 = new cpr.controls.layouts.XYLayout();
				group_3.setLayout(xYLayout_4);
				(function(container){
					var output_1 = new cpr.controls.Output("output_d142852d");
					output_1.value = "로그인";
					container.addChild(output_1, {
						"top": "19.0px",
						"left": "103.0px",
						"width": "154.54969787597656px",
						"height": "14.0px"
					});
				})(group_3);
				container.addChild(group_3, {
					"top": "570.0px",
					"left": "534.0px",
					"width": "360.0px",
					"height": "52.0px"
				});
				var group_4 = new cpr.controls.Container("group_1cabeada");
				group_4.style.css({
					"background-color" : "#5686C4"
				});
				var xYLayout_5 = new cpr.controls.layouts.XYLayout();
				group_4.setLayout(xYLayout_5);
				(function(container){
					var output_2 = new cpr.controls.Output("output_2bac5d3d");
					output_2.value = "계정 신청절차 안내";
					container.addChild(output_2, {
						"top": "19.0px",
						"left": "103.0px",
						"width": "154.54969787597656px",
						"height": "14.0px"
					});
				})(group_4);
				container.addChild(group_4, {
					"top": "570.0px",
					"left": "1015.0px",
					"width": "360.0px",
					"height": "52.0px"
				});
				var group_5 = new cpr.controls.Container("group_9f8568f0");
				var xYLayout_6 = new cpr.controls.layouts.XYLayout();
				group_5.setLayout(xYLayout_6);
				(function(container){
					var output_3 = new cpr.controls.Output("output_0c7a3cf3");
					output_3.value = "비밀번호";
					container.addChild(output_3, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "154.54969787597656px",
						"height": "14.0px"
					});
					var group_6 = new cpr.controls.Container("group_122bd8a6");
					group_6.style.css({
						"background-color" : "#FFFFFF",
						"border-bottom-color" : "#cfd0d2",
						"border-left-color" : "#cfd0d2",
						"border-top-color" : "#cfd0d2",
						"border-right-color" : "#cfd0d2"
					});
					var xYLayout_7 = new cpr.controls.layouts.XYLayout();
					group_6.setLayout(xYLayout_7);
					container.addChild(group_6, {
						"top": "18.0px",
						"left": "0.0px",
						"width": "360.0px",
						"height": "52.0px"
					});
					var output_4 = new cpr.controls.Output("output_5d9353e9");
					output_4.value = "비밀번호를 입력해주세요";
					container.addChild(output_4, {
						"top": "33.0px",
						"left": "16.0px",
						"width": "137.0px",
						"height": "21.0px"
					});
				})(group_5);
				container.addChild(group_5, {
					"top": "480.0px",
					"left": "534.0px",
					"width": "360.0px",
					"height": "70.0px"
				});
				var group_7 = new cpr.controls.Container("group_dced90f6");
				var xYLayout_8 = new cpr.controls.layouts.XYLayout();
				group_7.setLayout(xYLayout_8);
				(function(container){
					var output_5 = new cpr.controls.Output("output_7c8522f8");
					output_5.value = "아이디";
					container.addChild(output_5, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "154.54969787597656px",
						"height": "14.0px"
					});
					var group_8 = new cpr.controls.Container("group_74b50e55");
					group_8.style.css({
						"background-color" : "#FFFFFF",
						"border-bottom-color" : "#cfd0d2",
						"border-left-color" : "#cfd0d2",
						"border-top-color" : "#cfd0d2",
						"border-right-color" : "#cfd0d2"
					});
					var xYLayout_9 = new cpr.controls.layouts.XYLayout();
					group_8.setLayout(xYLayout_9);
					container.addChild(group_8, {
						"top": "18.0px",
						"left": "0.0px",
						"width": "360.0px",
						"height": "52.0px"
					});
					var output_6 = new cpr.controls.Output("output_579527b2");
					output_6.value = "아이디를 입력해주세요";
					container.addChild(output_6, {
						"top": "33.0px",
						"left": "16.0px",
						"width": "125.0px",
						"height": "21.0px"
					});
				})(group_7);
				container.addChild(group_7, {
					"top": "390.0px",
					"left": "534.0px",
					"width": "360.0px",
					"height": "70.0px"
				});
				var group_9 = new cpr.controls.Container("group_075f91ce");
				var xYLayout_10 = new cpr.controls.layouts.XYLayout();
				group_9.setLayout(xYLayout_10);
				(function(container){
					var output_7 = new cpr.controls.Output("output_c4c763b2");
					output_7.value = "비밀번호 찾기";
					container.addChild(output_7, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "77.0px",
						"height": "21.0px"
					});
				})(group_9);
				container.addChild(group_9, {
					"top": "640.0px",
					"left": "676.0px",
					"width": "77.0px",
					"height": "21.0px"
				});
				var output_8 = new cpr.controls.Output("output_28dde8cf");
				output_8.value = "로그인";
				container.addChild(output_8, {
					"top": "345.0px",
					"left": "534.0px",
					"width": "52.0px",
					"height": "25.0px"
				});
				var output_9 = new cpr.controls.Output("output_ecf20e4d");
				output_9.value = "시스템 문의";
				container.addChild(output_9, {
					"top": "637.0px",
					"left": "1035.0px",
					"width": "64.0px",
					"height": "18.0px"
				});
				var button_1 = new cpr.controls.Button("instance_c17b258e");
				button_1.value = "Button";
				container.addChild(button_1, {
					"top": "636.0px",
					"left": "1015.0px",
					"width": "20.0px",
					"height": "20.0px"
				});
				var output_10 = new cpr.controls.Output("output_fc72180a");
				output_10.value = "741-0100(아우리 통합지원센터) 743-4841(시스템 담당)";
				container.addChild(output_10, {
					"top": "636.0px",
					"left": "1109.0px",
					"width": "168.0px",
					"height": "39.0px"
				});
				var output_11 = new cpr.controls.Output("output_056b0863");
				output_11.value = "개인정보처리방침 COPYRIGHT 2012 BY INCHEON INTERNATIONAL AIRPORT CORPORATION. ALL RIGHTS RESERVED";
				container.addChild(output_11, {
					"top": "759.0px",
					"left": "651.0px",
					"width": "618.0px",
					"height": "18.0px"
				});
				var group_10 = new cpr.controls.Container("group_3207c527");
				var xYLayout_11 = new cpr.controls.layouts.XYLayout();
				group_10.setLayout(xYLayout_11);
				(function(container){
					var output_12 = new cpr.controls.Output("output_b2d00168");
					output_12.value = "정보연계포털";
					container.addChild(output_12, {
						"top": "6.0px",
						"left": "229.0px",
						"width": "102.0px",
						"height": "25.0px"
					});
				})(group_10);
				container.addChild(group_10, {
					"top": "254.0px",
					"left": "795.0px",
					"width": "331.0px",
					"height": "31.0px"
				});
				var group_11 = new cpr.controls.Container("group_f2bef307");
				var xYLayout_12 = new cpr.controls.layouts.XYLayout();
				group_11.setLayout(xYLayout_12);
				(function(container){
					var output_13 = new cpr.controls.Output("output_e9237051");
					output_13.value = "공지사항";
					container.addChild(output_13, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "69.0px",
						"height": "25.0px"
					});
					var group_12 = new cpr.controls.Container("group_242ee310");
					var xYLayout_13 = new cpr.controls.layouts.XYLayout();
					group_12.setLayout(xYLayout_13);
					(function(container){
						var output_14 = new cpr.controls.Output("output_e356e14d");
						output_14.value = "협업포털 개인정보 파기공지(2024.11.01)";
						container.addChild(output_14, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "227.0px",
							"height": "21px"
						});
						var output_15 = new cpr.controls.Output("output_c2792d41");
						output_15.value = "협업포털 개인정보 파기공지(2024.09.03)";
						container.addChild(output_15, {
							"top": "37.0px",
							"left": "0.0px",
							"width": "235.0px",
							"height": "21.0px"
						});
						var output_16 = new cpr.controls.Output("output_68ce8126");
						output_16.value = "[필독]Edge에서 협업포털 사용 조치방법";
						container.addChild(output_16, {
							"top": "74.0px",
							"left": "0.0px",
							"width": "222.0px",
							"height": "21.0px"
						});
						var output_17 = new cpr.controls.Output("output_50c7aeee");
						output_17.value = "협업포털 접속불가 및 지연 시 처리방법";
						container.addChild(output_17, {
							"top": "111.0px",
							"left": "0.0px",
							"width": "212.0px",
							"height": "21.0px"
						});
					})(group_12);
					container.addChild(group_12, {
						"top": "45.0px",
						"left": "12.0px",
						"width": "320.0px",
						"height": "132.0px"
					});
					var group_13 = new cpr.controls.Container("group_7c0510bd");
					var xYLayout_14 = new cpr.controls.layouts.XYLayout();
					group_13.setLayout(xYLayout_14);
					container.addChild(group_13, {
						"top": "49.0px",
						"left": "0.0px",
						"width": "12.0px",
						"height": "12.0px"
					});
					var group_14 = new cpr.controls.Container("group_4f17fb54");
					var xYLayout_15 = new cpr.controls.layouts.XYLayout();
					group_14.setLayout(xYLayout_15);
					container.addChild(group_14, {
						"top": "86.0px",
						"left": "0.0px",
						"width": "12.0px",
						"height": "12.0px"
					});
					var group_15 = new cpr.controls.Container("group_e1ceed09");
					var xYLayout_16 = new cpr.controls.layouts.XYLayout();
					group_15.setLayout(xYLayout_16);
					container.addChild(group_15, {
						"top": "123.0px",
						"left": "0.0px",
						"width": "12.0px",
						"height": "12.0px"
					});
					var group_16 = new cpr.controls.Container("group_dbe0bcd8");
					var xYLayout_17 = new cpr.controls.layouts.XYLayout();
					group_16.setLayout(xYLayout_17);
					container.addChild(group_16, {
						"top": "160.0px",
						"left": "0.0px",
						"width": "12.0px",
						"height": "12.0px"
					});
				})(group_11);
				container.addChild(group_11, {
					"top": "345.0px",
					"left": "1015.0px",
					"width": "372.0px",
					"height": "177.0px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0.0px",
				"left": "0.0px",
				"width": "1920.0px",
				"height": "940.0px"
			});
		}
	});
	app.title = "design56828";
	cpr.core.Platform.INSTANCE.register(app);
})();
