/*
 * App URI: 2025-04-04/design21468
 * Source Location: 2025-04-04/design21468.clx
 *
 * This file was generated by eXBuilder6 compiler(1.0.5542), Don't edit manually.
 */
(function() {
	var app = new cpr.core.App("2025-04-04/design21468", { 
		onPrepare: function(loader) {
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports) {
			var linker = {};
			// Start - User Script
			// Generated JavaScript File for design21468.clx
			console.log('JavaScript for design21468 loaded.');;
			// End - User Script
			
			// Header
			app.supportMedia("all", "default");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("group_5557f4b3");
			group_1.style.css({
				"background-color" : "#F6F6F7"
			});
			var xYLayout_2 = new cpr.controls.layouts.XYLayout();
			group_1.setLayout(xYLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container("group_7024880b");
				var xYLayout_3 = new cpr.controls.layouts.XYLayout();
				group_2.setLayout(xYLayout_3);
				(function(container){
					var group_3 = new cpr.controls.Container("group_0e7e3b11");
					var xYLayout_4 = new cpr.controls.layouts.XYLayout();
					group_3.setLayout(xYLayout_4);
					(function(container){
						var group_4 = new cpr.controls.Container("group_402988e9");
						var xYLayout_5 = new cpr.controls.layouts.XYLayout();
						group_4.setLayout(xYLayout_5);
						(function(container){
							var group_5 = new cpr.controls.Container("group_8e880c5c");
							var xYLayout_6 = new cpr.controls.layouts.XYLayout();
							group_5.setLayout(xYLayout_6);
							container.addChild(group_5, {
								"top": "10.8599853515625px",
								"left": "0.0px",
								"width": "41.3650016784668px",
								"height": "26.280000686645508px"
							});
							var group_6 = new cpr.controls.Container("group_b811c9c2");
							var xYLayout_7 = new cpr.controls.layouts.XYLayout();
							group_6.setLayout(xYLayout_7);
							(function(container){
								var group_7 = new cpr.controls.Container("group_87427ced");
								var xYLayout_8 = new cpr.controls.layouts.XYLayout();
								group_7.setLayout(xYLayout_8);
								(function(container){
									var button_1 = new cpr.controls.Button("instance_e9e63e8b");
									button_1.value = "Button";
									button_1.style.css({
										"background-color" : "#FFFFFF",
										"background-image" : "none"
									});
									container.addChild(button_1, {
										"top": "2.0px",
										"left": "2.0px",
										"width": "24.0px",
										"height": "24.0px"
									});
								})(group_7);
								container.addChild(group_7, {
									"top": "10.0px",
									"left": "10.0px",
									"width": "28.0px",
									"height": "28.0px"
								});
							})(group_6);
							container.addChild(group_6, {
								"top": "0.0px",
								"left": "73.36500549316406px",
								"width": "48.0px",
								"height": "48.0px"
							});
						})(group_4);
						container.addChild(group_4, {
							"top": "8.0px",
							"left": "32.0px",
							"width": "153.0px",
							"height": "48.0px"
						});
						var group_8 = new cpr.controls.Container("group_008e1943");
						var xYLayout_9 = new cpr.controls.layouts.XYLayout();
						group_8.setLayout(xYLayout_9);
						(function(container){
							var group_9 = new cpr.controls.Container("group_4e0277aa");
							var xYLayout_10 = new cpr.controls.layouts.XYLayout();
							group_9.setLayout(xYLayout_10);
							(function(container){
								var group_10 = new cpr.controls.Container("group_99586449");
								var xYLayout_11 = new cpr.controls.layouts.XYLayout();
								group_10.setLayout(xYLayout_11);
								(function(container){
									var button_2 = new cpr.controls.Button("instance_55ca0888");
									button_2.value = "Button";
									button_2.style.css({
										"background-color" : "#FFFFFF",
										"background-image" : "none"
									});
									container.addChild(button_2, {
										"top": "2.0px",
										"left": "2.0px",
										"width": "24.0px",
										"height": "24.0px"
									});
								})(group_10);
								container.addChild(group_10, {
									"top": "10.0px",
									"left": "10.0px",
									"width": "28.0px",
									"height": "28.0px"
								});
								var group_11 = new cpr.controls.Container("group_788fce4d");
								var xYLayout_12 = new cpr.controls.layouts.XYLayout();
								group_11.setLayout(xYLayout_12);
								container.addChild(group_11, {
									"top": "10.0px",
									"left": "32.0px",
									"width": "6.0px",
									"height": "6.0px"
								});
							})(group_9);
							container.addChild(group_9, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "48.0px",
								"height": "48.0px"
							});
							var group_12 = new cpr.controls.Container("group_d97cc69d");
							var xYLayout_13 = new cpr.controls.layouts.XYLayout();
							group_12.setLayout(xYLayout_13);
							(function(container){
								var group_13 = new cpr.controls.Container("group_5e209f3d");
								group_13.style.css({
									"background-color" : "#00ABB3"
								});
								var xYLayout_14 = new cpr.controls.layouts.XYLayout();
								group_13.setLayout(xYLayout_14);
								(function(container){
									var group_14 = new cpr.controls.Container("group_26dba28f");
									var xYLayout_15 = new cpr.controls.layouts.XYLayout();
									group_14.setLayout(xYLayout_15);
									container.addChild(group_14, {
										"top": "8.0px",
										"left": "8.0px",
										"width": "20.0px",
										"height": "20.0px"
									});
								})(group_13);
								container.addChild(group_13, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "36.0px",
									"height": "36.0px"
								});
								var group_15 = new cpr.controls.Container("group_392221df");
								var xYLayout_16 = new cpr.controls.layouts.XYLayout();
								group_15.setLayout(xYLayout_16);
								(function(container){
									var output_1 = new cpr.controls.Output("output_f1b3765f");
									output_1.value = "aidt003";
									container.addChild(output_1, {
										"top": "2.0px",
										"left": "0.0px",
										"width": "58.0px",
										"height": "20.0px"
									});
									var output_2 = new cpr.controls.Output("output_9690644e");
									output_2.value = "홍길동";
									container.addChild(output_2, {
										"top": "2.0px",
										"left": "66.0px",
										"width": "41.0px",
										"height": "20.0px"
									});
									var output_3 = new cpr.controls.Output("output_51b28603");
									output_3.value = "00:00:00";
									container.addChild(output_3, {
										"top": "0.0px",
										"left": "115.0px",
										"width": "66.0px",
										"height": "24.0px"
									});
								})(group_15);
								container.addChild(group_15, {
									"top": "6.0px",
									"left": "48.0px",
									"width": "181.0px",
									"height": "24.0px"
								});
							})(group_12);
							container.addChild(group_12, {
								"top": "6.0px",
								"left": "64.0px",
								"width": "229.0px",
								"height": "36.0px"
							});
						})(group_8);
						container.addChild(group_8, {
							"top": "8.0px",
							"left": "1595.0px",
							"width": "293.0px",
							"height": "48.0px"
						});
					})(group_3);
					container.addChild(group_3, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "1920.0px",
						"height": "64.0px"
					});
				})(group_2);
				container.addChild(group_2, {
					"top": "0.0px",
					"left": "0.0px",
					"width": "1920.0px",
					"height": "65.0px"
				});
				var group_16 = new cpr.controls.Container("group_3e274670");
				var xYLayout_17 = new cpr.controls.layouts.XYLayout();
				group_16.setLayout(xYLayout_17);
				(function(container){
					var group_17 = new cpr.controls.Container("group_eb1321a5");
					var xYLayout_18 = new cpr.controls.layouts.XYLayout();
					group_17.setLayout(xYLayout_18);
					(function(container){
						var group_18 = new cpr.controls.Container("group_3ded754e");
						var xYLayout_19 = new cpr.controls.layouts.XYLayout();
						group_18.setLayout(xYLayout_19);
						(function(container){
							var group_19 = new cpr.controls.Container("group_4e5db97b");
							var xYLayout_20 = new cpr.controls.layouts.XYLayout();
							group_19.setLayout(xYLayout_20);
							(function(container){
								var output_4 = new cpr.controls.Output("output_11f3b6cf");
								output_4.value = "정보연계 현황(종)";
								container.addChild(output_4, {
									"top": "0.0px",
									"left": "12.0px",
									"width": "111.0px",
									"height": "20.0px"
								});
							})(group_19);
							container.addChild(group_19, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "580.3099975585938px",
								"height": "20.0px"
							});
						})(group_18);
						container.addChild(group_18, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "580.3099975585938px",
							"height": "20.0px"
						});
					})(group_17);
					container.addChild(group_17, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "580.0px",
						"height": "20.0px"
					});
				})(group_16);
				container.addChild(group_16, {
					"top": "428.0px",
					"left": "70.0px",
					"width": "430.0px",
					"height": "20.0px"
				});
				var group_20 = new cpr.controls.Container("group_3dd57525");
				var xYLayout_21 = new cpr.controls.layouts.XYLayout();
				group_20.setLayout(xYLayout_21);
				(function(container){
					var group_21 = new cpr.controls.Container("group_2a5ba3b5");
					var xYLayout_22 = new cpr.controls.layouts.XYLayout();
					group_21.setLayout(xYLayout_22);
					(function(container){
						var group_22 = new cpr.controls.Container("group_e9d82b29");
						var xYLayout_23 = new cpr.controls.layouts.XYLayout();
						group_22.setLayout(xYLayout_23);
						(function(container){
							var group_23 = new cpr.controls.Container("group_116853f9");
							var xYLayout_24 = new cpr.controls.layouts.XYLayout();
							group_23.setLayout(xYLayout_24);
							(function(container){
								var output_5 = new cpr.controls.Output("output_1f6618e7");
								output_5.value = "메시지 처리 현황(Top 10)";
								container.addChild(output_5, {
									"top": "0.0px",
									"left": "12.0px",
									"width": "162.0px",
									"height": "20.0px"
								});
							})(group_23);
							container.addChild(group_23, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "580.3099975585938px",
								"height": "20.0px"
							});
						})(group_22);
						container.addChild(group_22, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "580.3099975585938px",
							"height": "20.0px"
						});
					})(group_21);
					container.addChild(group_21, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "580.0px",
						"height": "20.0px"
					});
				})(group_20);
				container.addChild(group_20, {
					"top": "656.0px",
					"left": "70.0px",
					"width": "430.0px",
					"height": "20.0px"
				});
				var group_24 = new cpr.controls.Container("group_77677694");
				var xYLayout_25 = new cpr.controls.layouts.XYLayout();
				group_24.setLayout(xYLayout_25);
				(function(container){
					var group_25 = new cpr.controls.Container("group_e2fa907f");
					var xYLayout_26 = new cpr.controls.layouts.XYLayout();
					group_25.setLayout(xYLayout_26);
					(function(container){
						var group_26 = new cpr.controls.Container("group_e6cf880e");
						var xYLayout_27 = new cpr.controls.layouts.XYLayout();
						group_26.setLayout(xYLayout_27);
						(function(container){
							var group_27 = new cpr.controls.Container("group_40b2c6df");
							var xYLayout_28 = new cpr.controls.layouts.XYLayout();
							group_27.setLayout(xYLayout_28);
							(function(container){
								var output_6 = new cpr.controls.Output("output_b15aad75");
								output_6.value = "단위시스템별 메시지 처리 현황(Top 10)";
								container.addChild(output_6, {
									"top": "0.0px",
									"left": "12.0px",
									"width": "246.0px",
									"height": "20.0px"
								});
							})(group_27);
							container.addChild(group_27, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "580.3099975585938px",
								"height": "20.0px"
							});
						})(group_26);
						container.addChild(group_26, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "580.3099975585938px",
							"height": "20.0px"
						});
					})(group_25);
					container.addChild(group_25, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "580.0px",
						"height": "20.0px"
					});
				})(group_24);
				container.addChild(group_24, {
					"top": "656.0px",
					"left": "970.0px",
					"width": "430.0px",
					"height": "20.0px"
				});
				var group_28 = new cpr.controls.Container("group_98f8f055");
				var xYLayout_29 = new cpr.controls.layouts.XYLayout();
				group_28.setLayout(xYLayout_29);
				(function(container){
					var group_29 = new cpr.controls.Container("group_6051de38");
					var xYLayout_30 = new cpr.controls.layouts.XYLayout();
					group_29.setLayout(xYLayout_30);
					(function(container){
						var group_30 = new cpr.controls.Container("group_f8beaba1");
						var xYLayout_31 = new cpr.controls.layouts.XYLayout();
						group_30.setLayout(xYLayout_31);
						(function(container){
							var group_31 = new cpr.controls.Container("group_160c3f40");
							var xYLayout_32 = new cpr.controls.layouts.XYLayout();
							group_31.setLayout(xYLayout_32);
							(function(container){
								var output_7 = new cpr.controls.Output("output_8922c258");
								output_7.value = "메시지 송수진 현황(건)";
								container.addChild(output_7, {
									"top": "0.0px",
									"left": "12.0px",
									"width": "141.0px",
									"height": "20.0px"
								});
							})(group_31);
							container.addChild(group_31, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "580.3099975585938px",
								"height": "20.0px"
							});
						})(group_30);
						container.addChild(group_30, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "580.3099975585938px",
							"height": "20.0px"
						});
					})(group_29);
					container.addChild(group_29, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "580.0px",
						"height": "20.0px"
					});
				})(group_28);
				container.addChild(group_28, {
					"top": "428.0px",
					"left": "520.0px",
					"width": "655.0px",
					"height": "20.0px"
				});
				var group_32 = new cpr.controls.Container("group_ff1d9be7");
				var xYLayout_33 = new cpr.controls.layouts.XYLayout();
				group_32.setLayout(xYLayout_33);
				(function(container){
					var group_33 = new cpr.controls.Container("group_270f8d35");
					var xYLayout_34 = new cpr.controls.layouts.XYLayout();
					group_33.setLayout(xYLayout_34);
					(function(container){
						var group_34 = new cpr.controls.Container("group_75ffe98f");
						var xYLayout_35 = new cpr.controls.layouts.XYLayout();
						group_34.setLayout(xYLayout_35);
						(function(container){
							var group_35 = new cpr.controls.Container("group_9e4328c1");
							var xYLayout_36 = new cpr.controls.layouts.XYLayout();
							group_35.setLayout(xYLayout_36);
							(function(container){
								var output_8 = new cpr.controls.Output("output_747ef587");
								output_8.value = "API서비스 이용현황(건)";
								container.addChild(output_8, {
									"top": "0.0px",
									"left": "12.0px",
									"width": "148.0px",
									"height": "20.0px"
								});
							})(group_35);
							container.addChild(group_35, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "580.3099975585938px",
								"height": "20.0px"
							});
						})(group_34);
						container.addChild(group_34, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "580.3099975585938px",
							"height": "20.0px"
						});
					})(group_33);
					container.addChild(group_33, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "580.0px",
						"height": "20.0px"
					});
				})(group_32);
				container.addChild(group_32, {
					"top": "428.0px",
					"left": "1195.0px",
					"width": "655.0px",
					"height": "20.0px"
				});
				var group_36 = new cpr.controls.Container("group_3a121bcd");
				var xYLayout_37 = new cpr.controls.layouts.XYLayout();
				group_36.setLayout(xYLayout_37);
				(function(container){
					var output_9 = new cpr.controls.Output("output_fed67ae9");
					output_9.value = "정보연계 신청";
					container.addChild(output_9, {
						"top": "15.0px",
						"left": "14.0px",
						"width": "86.0px",
						"height": "23.0px"
					});
					var output_10 = new cpr.controls.Output("output_6f8c905e");
					output_10.value = "결재 대기함";
					container.addChild(output_10, {
						"top": "78.0px",
						"left": "14.0px",
						"width": "72.0px",
						"height": "23.0px"
					});
					var output_11 = new cpr.controls.Output("output_649f6d74");
					output_11.value = "10건";
					container.addChild(output_11, {
						"top": "9.0px",
						"left": "134.0px",
						"width": "32.0px",
						"height": "34.0px"
					});
					var output_12 = new cpr.controls.Output("output_0d1b91b5");
					output_12.value = "30건";
					container.addChild(output_12, {
						"top": "73.0px",
						"left": "134.0px",
						"width": "35.0px",
						"height": "34.0px"
					});
				})(group_36);
				container.addChild(group_36, {
					"top": "171.0px",
					"left": "553.0px",
					"width": "180.0px",
					"height": "117.0px"
				});
				var grid_1 = new cpr.controls.Grid("grd63e1aae3");
				grid_1.init({
					"columns": [
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"}
					],
					"header": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
								}
							}
						]
					},
					"detail": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
								}
							}
						]
					}
				});
				container.addChild(grid_1, {
					"top": "171.0px",
					"left": "70.0px",
					"width": "472.9991455078125px",
					"height": "116.5px"
				});
				var output_13 = new cpr.controls.Output("output_c49c13c3");
				output_13.value = "120";
				container.addChild(output_13, {
					"top": "259.0px",
					"left": "814.0px",
					"width": "109.0px",
					"height": "20.0px"
				});
				var output_14 = new cpr.controls.Output("output_2cd8c6fa");
				output_14.value = "30";
				container.addChild(output_14, {
					"top": "259.0px",
					"left": "923.0px",
					"width": "109.0px",
					"height": "20.0px"
				});
				var output_15 = new cpr.controls.Output("output_fed132bb");
				output_15.value = "20";
				container.addChild(output_15, {
					"top": "259.0px",
					"left": "1033.0px",
					"width": "110.0px",
					"height": "20.0px"
				});
				var output_16 = new cpr.controls.Output("output_86c319c8");
				output_16.value = "10";
				container.addChild(output_16, {
					"top": "259.0px",
					"left": "1144.0px",
					"width": "110.0px",
					"height": "20.0px"
				});
				var output_17 = new cpr.controls.Output("output_2bdf6d09");
				output_17.value = "32";
				container.addChild(output_17, {
					"top": "259.0px",
					"left": "1255.0px",
					"width": "110.0px",
					"height": "20.0px"
				});
				var output_18 = new cpr.controls.Output("output_69211161");
				output_18.value = "32";
				container.addChild(output_18, {
					"top": "259.0px",
					"left": "1366.0px",
					"width": "110.0px",
					"height": "20.0px"
				});
				var grid_2 = new cpr.controls.Grid("grde4774210");
				grid_2.init({
					"columns": [
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"}
					],
					"header": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
								}
							}
						]
					},
					"detail": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
								}
							}
						]
					}
				});
				container.addChild(grid_2, {
					"top": "171.0px",
					"left": "813.0px",
					"width": "663.0001831054688px",
					"height": "117.0px"
				});
				var group_37 = new cpr.controls.Container("group_aed18615");
				var xYLayout_38 = new cpr.controls.layouts.XYLayout();
				group_37.setLayout(xYLayout_38);
				(function(container){
					var group_38 = new cpr.controls.Container("group_e6f514fe");
					var xYLayout_39 = new cpr.controls.layouts.XYLayout();
					group_38.setLayout(xYLayout_39);
					(function(container){
						var output_19 = new cpr.controls.Output("output_f5ba09d3");
						output_19.value = "협업포털 개인정보 파기공지(2024.11.01)";
						container.addChild(output_19, {
							"top": "0.0px",
							"left": "0.0px",
							"width": "227.0px",
							"height": "21.0px"
						});
						var output_20 = new cpr.controls.Output("output_b7666666");
						output_20.value = "협업포털 개인정보 파기공지(2024.09.03)";
						container.addChild(output_20, {
							"top": "37.0px",
							"left": "0.0px",
							"width": "235.0px",
							"height": "21.0px"
						});
						var output_21 = new cpr.controls.Output("output_4f71cef4");
						output_21.value = "[필독]Edge에서 협업포털 사용 조치방법";
						container.addChild(output_21, {
							"top": "74.0px",
							"left": "0.0px",
							"width": "222.0px",
							"height": "21.0px"
						});
						var output_22 = new cpr.controls.Output("output_b3636aed");
						output_22.value = "협업포털 접속불가 및 지연 시 처리방법";
						container.addChild(output_22, {
							"top": "111.0px",
							"left": "0.0px",
							"width": "212.0px",
							"height": "21.0px"
						});
					})(group_38);
					container.addChild(group_38, {
						"top": "0.0px",
						"left": "9.4842529296875px",
						"width": "252.90322875976562px",
						"height": "132.0px"
					});
					var group_39 = new cpr.controls.Container("group_1d111fb5");
					var xYLayout_40 = new cpr.controls.layouts.XYLayout();
					group_39.setLayout(xYLayout_40);
					container.addChild(group_39, {
						"top": "4.0px",
						"left": "0.0px",
						"width": "9.483870506286621px",
						"height": "12.0px"
					});
					var group_40 = new cpr.controls.Container("group_3789f82b");
					var xYLayout_41 = new cpr.controls.layouts.XYLayout();
					group_40.setLayout(xYLayout_41);
					container.addChild(group_40, {
						"top": "41.0px",
						"left": "0.0px",
						"width": "9.483870506286621px",
						"height": "12.0px"
					});
					var group_41 = new cpr.controls.Container("group_a5ed14e6");
					var xYLayout_42 = new cpr.controls.layouts.XYLayout();
					group_41.setLayout(xYLayout_42);
					container.addChild(group_41, {
						"top": "78.0px",
						"left": "0.0px",
						"width": "9.483870506286621px",
						"height": "12.0px"
					});
					var group_42 = new cpr.controls.Container("group_38799e8f");
					var xYLayout_43 = new cpr.controls.layouts.XYLayout();
					group_42.setLayout(xYLayout_43);
					container.addChild(group_42, {
						"top": "115.0px",
						"left": "0.0px",
						"width": "9.483870506286621px",
						"height": "12.0px"
					});
				})(group_37);
				container.addChild(group_37, {
					"top": "171.0px",
					"left": "1556.0px",
					"width": "294.0px",
					"height": "132.0px"
				});
				var group_43 = new cpr.controls.Container("group_5327ed6a");
				var xYLayout_44 = new cpr.controls.layouts.XYLayout();
				group_43.setLayout(xYLayout_44);
				(function(container){
					var output_23 = new cpr.controls.Output("output_2dc2cf32");
					output_23.value = "나의 업무 현황";
					container.addChild(output_23, {
						"top": "0.5px",
						"left": "0.0px",
						"width": "639.280029296875px",
						"height": "25.0px"
					});
					var group_44 = new cpr.controls.Container("group_3ac403de");
					group_44.style.css({
						"background-color" : "#FFFFFF",
						"border-bottom-color" : "#bbbbbe",
						"border-left-color" : "#bbbbbe",
						"border-top-color" : "#bbbbbe",
						"border-right-color" : "#bbbbbe"
					});
					var xYLayout_45 = new cpr.controls.layouts.XYLayout();
					group_44.setLayout(xYLayout_45);
					(function(container){
						var group_45 = new cpr.controls.Container("group_9b615fe7");
						var xYLayout_46 = new cpr.controls.layouts.XYLayout();
						group_45.setLayout(xYLayout_46);
						(function(container){
							var group_46 = new cpr.controls.Container("group_9fbefb6a");
							var xYLayout_47 = new cpr.controls.layouts.XYLayout();
							group_46.setLayout(xYLayout_47);
							(function(container){
								var group_47 = new cpr.controls.Container("group_297818cb");
								var xYLayout_48 = new cpr.controls.layouts.XYLayout();
								group_47.setLayout(xYLayout_48);
								container.addChild(group_47, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "18.0px",
									"height": "18.0px"
								});
							})(group_46);
							container.addChild(group_46, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "18.0px",
								"height": "18.0px"
							});
						})(group_45);
						container.addChild(group_45, {
							"top": "4.0px",
							"left": "9.0px",
							"width": "18.0px",
							"height": "18.0px"
						});
						var output_24 = new cpr.controls.Output("output_841b6283");
						output_24.value = "more";
						container.addChild(output_24, {
							"top": "6.5px",
							"left": "31.0px",
							"width": "34.0px",
							"height": "13.0px"
						});
					})(group_44);
					container.addChild(group_44, {
						"top": "0.0px",
						"left": "649.280029296875px",
						"width": "73.72000122070312px",
						"height": "26.0px"
					});
				})(group_43);
				container.addChild(group_43, {
					"top": "105.0px",
					"left": "40.0px",
					"width": "723.0px",
					"height": "26.0px"
				});
				var group_48 = new cpr.controls.Container("group_242dde3c");
				var xYLayout_49 = new cpr.controls.layouts.XYLayout();
				group_48.setLayout(xYLayout_49);
				(function(container){
					var output_25 = new cpr.controls.Output("output_ae6a3e27");
					output_25.value = "정보연계 현황";
					container.addChild(output_25, {
						"top": "0.0px",
						"left": "0.0px",
						"width": "723.0px",
						"height": "25.0px"
					});
				})(group_48);
				container.addChild(group_48, {
					"top": "363.0px",
					"left": "40.0px",
					"width": "723.0px",
					"height": "25.0px"
				});
				var group_49 = new cpr.controls.Container("group_3b249b2e");
				var xYLayout_50 = new cpr.controls.layouts.XYLayout();
				group_49.setLayout(xYLayout_50);
				(function(container){
					var output_26 = new cpr.controls.Output("output_94512352");
					output_26.value = "정보연계 진행 현황";
					container.addChild(output_26, {
						"top": "0.5px",
						"left": "0.0px",
						"width": "639.280029296875px",
						"height": "25.0px"
					});
					var group_50 = new cpr.controls.Container("group_70d3056d");
					group_50.style.css({
						"background-color" : "#FFFFFF",
						"border-bottom-color" : "#bbbbbe",
						"border-left-color" : "#bbbbbe",
						"border-top-color" : "#bbbbbe",
						"border-right-color" : "#bbbbbe"
					});
					var xYLayout_51 = new cpr.controls.layouts.XYLayout();
					group_50.setLayout(xYLayout_51);
					(function(container){
						var group_51 = new cpr.controls.Container("group_f168d365");
						var xYLayout_52 = new cpr.controls.layouts.XYLayout();
						group_51.setLayout(xYLayout_52);
						(function(container){
							var group_52 = new cpr.controls.Container("group_cc56f9c1");
							var xYLayout_53 = new cpr.controls.layouts.XYLayout();
							group_52.setLayout(xYLayout_53);
							(function(container){
								var group_53 = new cpr.controls.Container("group_375d7506");
								var xYLayout_54 = new cpr.controls.layouts.XYLayout();
								group_53.setLayout(xYLayout_54);
								container.addChild(group_53, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "18.0px",
									"height": "18.0px"
								});
							})(group_52);
							container.addChild(group_52, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "18.0px",
								"height": "18.0px"
							});
						})(group_51);
						container.addChild(group_51, {
							"top": "4.0px",
							"left": "9.0px",
							"width": "18.0px",
							"height": "18.0px"
						});
						var output_27 = new cpr.controls.Output("output_96e6c89d");
						output_27.value = "more";
						container.addChild(output_27, {
							"top": "6.5px",
							"left": "31.0px",
							"width": "34.0px",
							"height": "13.0px"
						});
					})(group_50);
					container.addChild(group_50, {
						"top": "0.0px",
						"left": "649.280029296875px",
						"width": "73.72000122070312px",
						"height": "26.0px"
					});
				})(group_49);
				container.addChild(group_49, {
					"top": "105.0px",
					"left": "783.0px",
					"width": "723.0px",
					"height": "26.0px"
				});
				var group_54 = new cpr.controls.Container("group_fd194e76");
				var xYLayout_55 = new cpr.controls.layouts.XYLayout();
				group_54.setLayout(xYLayout_55);
				(function(container){
					var output_28 = new cpr.controls.Output("output_630d8ad3");
					output_28.value = "공지사항";
					container.addChild(output_28, {
						"top": "0.5px",
						"left": "0.0px",
						"width": "270.2799987792969px",
						"height": "25.0px"
					});
					var group_55 = new cpr.controls.Container("group_ce1a1106");
					group_55.style.css({
						"background-color" : "#FFFFFF",
						"border-bottom-color" : "#bbbbbe",
						"border-left-color" : "#bbbbbe",
						"border-top-color" : "#bbbbbe",
						"border-right-color" : "#bbbbbe"
					});
					var xYLayout_56 = new cpr.controls.layouts.XYLayout();
					group_55.setLayout(xYLayout_56);
					(function(container){
						var group_56 = new cpr.controls.Container("group_3758383c");
						var xYLayout_57 = new cpr.controls.layouts.XYLayout();
						group_56.setLayout(xYLayout_57);
						(function(container){
							var group_57 = new cpr.controls.Container("group_96b4870a");
							var xYLayout_58 = new cpr.controls.layouts.XYLayout();
							group_57.setLayout(xYLayout_58);
							(function(container){
								var group_58 = new cpr.controls.Container("group_4512b917");
								var xYLayout_59 = new cpr.controls.layouts.XYLayout();
								group_58.setLayout(xYLayout_59);
								container.addChild(group_58, {
									"top": "0.0px",
									"left": "0.0px",
									"width": "18.0px",
									"height": "18.0px"
								});
							})(group_57);
							container.addChild(group_57, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "18.0px",
								"height": "18.0px"
							});
						})(group_56);
						container.addChild(group_56, {
							"top": "4.0px",
							"left": "9.0px",
							"width": "18.0px",
							"height": "18.0px"
						});
						var output_29 = new cpr.controls.Output("output_6fe054fd");
						output_29.value = "more";
						container.addChild(output_29, {
							"top": "6.5px",
							"left": "31.0px",
							"width": "34.0px",
							"height": "13.0px"
						});
					})(group_55);
					container.addChild(group_55, {
						"top": "0.0px",
						"left": "280.280029296875px",
						"width": "73.72000122070312px",
						"height": "26.0px"
					});
				})(group_54);
				container.addChild(group_54, {
					"top": "105.0px",
					"left": "1526.0px",
					"width": "354.0px",
					"height": "26.0px"
				});
				var output_30 = new cpr.controls.Output("output_24e6e14d");
				output_30.value = "송신+수신";
				container.addChild(output_30, {
					"top": "716.0px",
					"left": "106.0px",
					"width": "54.0px",
					"height": "20.0px"
				});
				var output_31 = new cpr.controls.Output("output_4e9db87e");
				output_31.value = "송신";
				container.addChild(output_31, {
					"top": "744.0px",
					"left": "106.0px",
					"width": "23.0px",
					"height": "20.0px"
				});
				var output_32 = new cpr.controls.Output("output_84bb2355");
				output_32.value = "수신";
				container.addChild(output_32, {
					"top": "772.0px",
					"left": "106.0px",
					"width": "23.0px",
					"height": "20.0px"
				});
				var output_33 = new cpr.controls.Output("output_ee06d1c7");
				output_33.value = "송신+수신";
				container.addChild(output_33, {
					"top": "716.0px",
					"left": "1006.0px",
					"width": "54.0px",
					"height": "20.0px"
				});
				var output_34 = new cpr.controls.Output("output_70977809");
				output_34.value = "송신";
				container.addChild(output_34, {
					"top": "744.0px",
					"left": "1006.0px",
					"width": "23.0px",
					"height": "20.0px"
				});
				var output_35 = new cpr.controls.Output("output_4376e875");
				output_35.value = "수신";
				container.addChild(output_35, {
					"top": "772.0px",
					"left": "1006.0px",
					"width": "23.0px",
					"height": "20.0px"
				});
				var output_36 = new cpr.controls.Output("output_798d09e7");
				output_36.value = "단위시스템";
				container.addChild(output_36, {
					"top": "488.0px",
					"left": "118.0px",
					"width": "61.0px",
					"height": "21.0px"
				});
				var output_37 = new cpr.controls.Output("output_286f590f");
				output_37.value = "298";
				container.addChild(output_37, {
					"top": "541.0px",
					"left": "126.0px",
					"width": "45.0px",
					"height": "30.0px"
				});
				var output_38 = new cpr.controls.Output("output_62179239");
				output_38.value = "155";
				container.addChild(output_38, {
					"top": "541.0px",
					"left": "266.0px",
					"width": "41.0px",
					"height": "30.0px"
				});
				var output_39 = new cpr.controls.Output("output_299ad954");
				output_39.value = "5";
				container.addChild(output_39, {
					"top": "541.0px",
					"left": "415.0px",
					"width": "16.0px",
					"height": "30.0px"
				});
				var output_40 = new cpr.controls.Output("output_13a26b97");
				output_40.value = "MDD";
				container.addChild(output_40, {
					"top": "488.0px",
					"left": "270.0px",
					"width": "32.0px",
					"height": "21.0px"
				});
				var output_41 = new cpr.controls.Output("output_c71f8007");
				output_41.value = "API";
				container.addChild(output_41, {
					"top": "488.0px",
					"left": "413.0px",
					"width": "21.0px",
					"height": "21.0px"
				});
				var group_59 = new cpr.controls.Container("group_d40cde66");
				group_59.style.css({
					"background-color" : "#FFFFFF",
					"border-bottom-color" : "#e2e2e3",
					"border-left-color" : "#e2e2e3",
					"border-top-color" : "#e2e2e3",
					"border-right-color" : "#e2e2e3"
				});
				var xYLayout_60 = new cpr.controls.layouts.XYLayout();
				group_59.setLayout(xYLayout_60);
				(function(container){
					var group_60 = new cpr.controls.Container("group_8d61a8db");
					var xYLayout_61 = new cpr.controls.layouts.XYLayout();
					group_60.setLayout(xYLayout_61);
					(function(container){
						var output_42 = new cpr.controls.Output("output_cfdf961c");
						output_42.value = "일간";
						container.addChild(output_42, {
							"top": "18.0px",
							"left": "90.0px",
							"width": "25.0px",
							"height": "21.0px"
						});
						var output_43 = new cpr.controls.Output("output_008ae7e3");
						output_43.value = "월간";
						container.addChild(output_43, {
							"top": "18.0px",
							"left": "303.0px",
							"width": "25.0px",
							"height": "21.0px"
						});
						var output_44 = new cpr.controls.Output("output_c24f1259");
						output_44.value = "연간";
						container.addChild(output_44, {
							"top": "18.0px",
							"left": "514.0px",
							"width": "25.0px",
							"height": "21.0px"
						});
						var output_45 = new cpr.controls.Output("output_041321e1");
						output_45.value = "11,763,720";
						container.addChild(output_45, {
							"top": "64.0px",
							"left": "43.0px",
							"width": "118.0px",
							"height": "30.0px"
						});
						var output_46 = new cpr.controls.Output("output_1c996d3c");
						output_46.value = "364,675,320";
						container.addChild(output_46, {
							"top": "64.0px",
							"left": "243.0px",
							"width": "144.0px",
							"height": "30.0px"
						});
						var output_47 = new cpr.controls.Output("output_9792a156");
						output_47.value = "4,293,757,800";
						container.addChild(output_47, {
							"top": "64.0px",
							"left": "446.0px",
							"width": "161.0px",
							"height": "30.0px"
						});
						var group_61 = new cpr.controls.Container("group_6b991802");
						var xYLayout_62 = new cpr.controls.layouts.XYLayout();
						group_61.setLayout(xYLayout_62);
						(function(container){
							var output_48 = new cpr.controls.Output("output_af196dfc");
							output_48.value = "전일 대비";
							container.addChild(output_48, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "52.0px",
								"height": "21.0px"
							});
							var output_49 = new cpr.controls.Output("output_d91ed526");
							output_49.value = "8,451";
							container.addChild(output_49, {
								"top": "1.5px",
								"left": "70.0px",
								"width": "37.0px",
								"height": "18.0px"
							});
						})(group_61);
						container.addChild(group_61, {
							"top": "102.0px",
							"left": "49.0px",
							"width": "107.0px",
							"height": "21.0px"
						});
						var group_62 = new cpr.controls.Container("group_82f4da8a");
						var xYLayout_63 = new cpr.controls.layouts.XYLayout();
						group_62.setLayout(xYLayout_63);
						(function(container){
							var output_50 = new cpr.controls.Output("output_3f410612");
							output_50.value = "전월 대비";
							container.addChild(output_50, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "52.0px",
								"height": "21.0px"
							});
							var output_51 = new cpr.controls.Output("output_dcaf88f8");
							output_51.value = "561,541";
							container.addChild(output_51, {
								"top": "1.5px",
								"left": "70.0px",
								"width": "52.0px",
								"height": "18.0px"
							});
						})(group_62);
						container.addChild(group_62, {
							"top": "101.0px",
							"left": "254.0px",
							"width": "122.0px",
							"height": "21.0px"
						});
					})(group_60);
					container.addChild(group_60, {
						"top": "14.0px",
						"left": "14.0px",
						"width": "627.0px",
						"height": "142.0px"
					});
				})(group_59);
				container.addChild(group_59, {
					"top": "456.0px",
					"left": "520.0px",
					"width": "655.0px",
					"height": "170.0px"
				});
				var group_63 = new cpr.controls.Container("group_a9c08f0f");
				group_63.style.css({
					"background-color" : "#FFFFFF",
					"border-bottom-color" : "#e2e2e3",
					"border-left-color" : "#e2e2e3",
					"border-top-color" : "#e2e2e3",
					"border-right-color" : "#e2e2e3"
				});
				var xYLayout_64 = new cpr.controls.layouts.XYLayout();
				group_63.setLayout(xYLayout_64);
				(function(container){
					var group_64 = new cpr.controls.Container("group_5ad5eedc");
					var xYLayout_65 = new cpr.controls.layouts.XYLayout();
					group_64.setLayout(xYLayout_65);
					(function(container){
						var output_52 = new cpr.controls.Output("output_1410f6ff");
						output_52.value = "일간";
						container.addChild(output_52, {
							"top": "18.0px",
							"left": "90.0px",
							"width": "25.0px",
							"height": "21.0px"
						});
						var output_53 = new cpr.controls.Output("output_4acf0288");
						output_53.value = "월간";
						container.addChild(output_53, {
							"top": "18.0px",
							"left": "303.0px",
							"width": "25.0px",
							"height": "21.0px"
						});
						var output_54 = new cpr.controls.Output("output_67839fb0");
						output_54.value = "연간";
						container.addChild(output_54, {
							"top": "18.0px",
							"left": "514.0px",
							"width": "25.0px",
							"height": "21.0px"
						});
						var output_55 = new cpr.controls.Output("output_fd70e4de");
						output_55.value = "63,570";
						container.addChild(output_55, {
							"top": "64.0px",
							"left": "63.0px",
							"width": "79.0px",
							"height": "30.0px"
						});
						var output_56 = new cpr.controls.Output("output_7b70df84");
						output_56.value = "175,320";
						container.addChild(output_56, {
							"top": "64.0px",
							"left": "270.0px",
							"width": "89.0px",
							"height": "30.0px"
						});
						var group_65 = new cpr.controls.Container("group_e6d56e2c");
						var xYLayout_66 = new cpr.controls.layouts.XYLayout();
						group_65.setLayout(xYLayout_66);
						(function(container){
							var output_57 = new cpr.controls.Output("output_94ea9d8c");
							output_57.value = "전일 대비";
							container.addChild(output_57, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "52.0px",
								"height": "21.0px"
							});
							var output_58 = new cpr.controls.Output("output_33576174");
							output_58.value = "451";
							container.addChild(output_58, {
								"top": "1.5px",
								"left": "70.0px",
								"width": "25.0px",
								"height": "18.0px"
							});
						})(group_65);
						container.addChild(group_65, {
							"top": "102.0px",
							"left": "55.0px",
							"width": "95.0px",
							"height": "21.0px"
						});
						var group_66 = new cpr.controls.Container("group_5e2b27b1");
						var xYLayout_67 = new cpr.controls.layouts.XYLayout();
						group_66.setLayout(xYLayout_67);
						(function(container){
							var output_59 = new cpr.controls.Output("output_8927985e");
							output_59.value = "전월 대비";
							container.addChild(output_59, {
								"top": "0.0px",
								"left": "0.0px",
								"width": "52.0px",
								"height": "21.0px"
							});
							var output_60 = new cpr.controls.Output("output_b67ec508");
							output_60.value = "1,541";
							container.addChild(output_60, {
								"top": "1.5px",
								"left": "70.0px",
								"width": "34.0px",
								"height": "18.0px"
							});
						})(group_66);
						container.addChild(group_66, {
							"top": "102.0px",
							"left": "267.0px",
							"width": "104.0px",
							"height": "21.0px"
						});
						var output_61 = new cpr.controls.Output("output_0973187c");
						output_61.value = "33,757,800";
						container.addChild(output_61, {
							"top": "64.0px",
							"left": "464.0px",
							"width": "125.0px",
							"height": "30.0px"
						});
					})(group_64);
					container.addChild(group_64, {
						"top": "14.0px",
						"left": "14.0px",
						"width": "627.0px",
						"height": "142.0px"
					});
				})(group_63);
				container.addChild(group_63, {
					"top": "456.0px",
					"left": "1195.0px",
					"width": "655.0px",
					"height": "170.0px"
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "0.0px",
				"left": "0.0px",
				"width": "1920.0px",
				"height": "940.0px"
			});
		}
	});
	app.title = "design21468";
	cpr.core.Platform.INSTANCE.register(app);
})();
